unicef/etools

EquiTrack/partners/views.py

Add update / patch option to partner API

---

etools-build.docker
frontend/build.sh
frontend_build/build.sh

fix build issues

---

EquiTrack/templates/map.html

add scrollable attribute for paper-tabs

---

EquiTrack/partners/models.py

fixed Nonetype issue with total_cash_transfered function

---

EquiTrack/partners/admin.py

fix distribution items checkbox readonly

---

.gitignore
EquiTrack/templates/admin/base.html
EquiTrack/templates/admin/base_site.html
EquiTrack/templates/base.html

display testing-environment bar on stools-dev and staging
update gitignore

environment tweaks

---

frontend/app/elements/common/etools-alert/etools-alert.html

fix closing tag

---

EquiTrack/partners/forms.py

added validation for letters in numeric fields
handle % for targets

Fix workplan upload

---

EquiTrack/templates/partners/pca_pdf.html

Small changes to PCA pdf render [Finishes #101920298] in pivotal tracker

Small changes to PCA pdf render

---

EquiTrack/trips/admin.py

temporary remove ability to add trip funds

Hot fix - adding trip runs 9k sql queries

---

EquiTrack/partners/admin.py
EquiTrack/partners/migrations/0059_auto_20160621_2228.py
EquiTrack/partners/models.py

Editable reference number in Agreements, Interventions and government interventions

Reference number

---

EquiTrack/partners/templatetags/intervention_tags.py
EquiTrack/vision/tasks.py

fix government ntervention implementation status

---

EquiTrack/requirements/base.txt

fix-circle-ci-build

---

EquiTrack/partners/forms.py
EquiTrack/partners/models.py

Agreement validation updates.
Only one PCA active at one time.

Agreement Validation

---

dev_environ_setup_linux.md

Linux/Ubuntu developer setup guide

docs(guide): new dev setup guide for linux/ubuntu

---

EquiTrack/locations/tasks.py

added new query with parent_col 
updated exception handling for parent_col

fixed import for parent_col

---

EquiTrack/locations/tasks.py

carto location msg

---

EquiTrack/reports/migrations/0018_auto_20160811_1654.py
EquiTrack/reports/models.py
EquiTrack/vision/adapters/funding.py

Changed Funding type column
Added more chars to indicator name

fix funding and ram sync

---

EquiTrack/EquiTrack/settings/base.py

broker visibility timeout in env var

broker visibility timeout in env

---

EquiTrack/EquiTrack/settings/production.py

allow 30 seconds for time difference between adfs server and etools server

Update ADFS slack time

---

EquiTrack/partners/views.py
EquiTrack/templates/map.html

Fix locations map 500 error

---

EquiTrack/EquiTrack/settings/production.py

Revert "Develop"

---

EquiTrack/partners/migrations/0065_auto_20160826_2024.py
EquiTrack/partners/migrations/0066_auto_20160826_2026.py
EquiTrack/partners/models.py
EquiTrack/vision/adapters/partner.py

partners get total cash even if negative decimal

fix vision sync

---

EquiTrack/EquiTrack/util_scripts.py
EquiTrack/vision/adapters/partner.py
EquiTrack/vision/adapters/programme.py

Updated util_scripts

---

EquiTrack/EquiTrack/util_scripts.py
EquiTrack/vision/adapters/partner.py
EquiTrack/vision/adapters/programme.py

Fix result structure 001 nik

---

EquiTrack/EquiTrack/urls.py
EquiTrack/EquiTrack/util_scripts.py
EquiTrack/templates/base.html

temporarily remove hact dashboard

---

EquiTrack/trips/exports.py

Changing the trips export per requirements from Lebanon CO.

Change trips export

---

EquiTrack/EquiTrack/urls.py
EquiTrack/partners/admin.py
EquiTrack/partners/models.py
EquiTrack/partners/serializers/partner_organization_v2.py
EquiTrack/partners/tests/test_exports.py
EquiTrack/partners/tests/test_views.py
EquiTrack/partners/urls_v2.py
EquiTrack/partners/views/partner_organization_v2.py
EquiTrack/partners/views/v2.py
EquiTrack/reports/serializers/v1.py
EquiTrack/reports/tests/test_views.py
EquiTrack/reports/urls_v2.py
EquiTrack/reports/views/v2.py
EquiTrack/trips/tests/test_views.py

APIs used in fronted dropdown for PMP

Dropdown APIs for PMP

---

EquiTrack/users/urls.py
EquiTrack/users/views.py

Get userprofile by id API

---

EquiTrack/partners/tests/test_views.py
EquiTrack/partners/validation/agreements.py

Fix signoff max date validation

---

EquiTrack/t2f/tests/test_vision_export.py
EquiTrack/t2f/vision.py

See footnote at
https://docs.python.org/2/library/xml.etree.elementtree.html

Fix invalid utf8 format

---

EquiTrack/vision/adapters/partner.py

Quick fix for National / International CSO

---

EquiTrack/partners/models.py

closes unicef/etools-issues#146

test waffle

---

EquiTrack/t2f/serializers/mailing.py
EquiTrack/t2f/tests/test_mailing.py

fixes unicef/etools-issues#96
fixes unicef/etools-issues#98
fixes unicef/etools-issues#100

Fix mailing serializer

---

EquiTrack/publics/serializers.py
EquiTrack/publics/tests/test_wbs_grant_fund_endpoint.py

Fixes unicef/etools-issues#182

Business area fallback

---

EquiTrack/t2f/models.py
EquiTrack/t2f/serializers/travel.py
EquiTrack/t2f/tests/test_overlapping_trips.py
EquiTrack/t2f/tests/test_travel_details.py

Check overlapping trips

---

EquiTrack/t2f/models.py
EquiTrack/t2f/tests/test_travel_details.py

fixes unicef/etools-issues#108

Change wording

---

EquiTrack/t2f/models.py
EquiTrack/t2f/tests/test_state_machine.py

fixes unicef/etools-issues#336

Expenses are not mandatory

---

EquiTrack/t2f/models.py

Connects https://github.com/unicef/etools-issues/issues/83

Add reference number on InvoiceItem admin instead of object

---

EquiTrack/locations/serializers.py
EquiTrack/locations/tests/test_views.py

Connects https://github.com/unicef/etools-issues/issues/78

Add location type, pcode to location name

---

EquiTrack/t2f/helpers/cost_summary_calculator.py
EquiTrack/t2f/tests/test_overlapping_trips.py

fixes unicef/etools-issues#395
fixes unicef/etools-issues#76

Fix rate getting

---

EquiTrack/t2f/helpers/cost_summary_calculator.py
EquiTrack/t2f/tests/test_cost_summary_calculator.py

fixes unicef  etools-issues#95 but needs frontend work too

- fix cost summary calculation

---

EquiTrack/t2f/models.py
EquiTrack/t2f/serializers/travel.py
EquiTrack/t2f/tests/test_treshold.py

Connects https://github.com/unicef/etools-issues/issues/400

Override start and end date based on itinerary, if present

---

EquiTrack/t2f/helpers/cost_summary_calculator.py
EquiTrack/t2f/models.py
EquiTrack/t2f/tests/test_exports.py
EquiTrack/t2f/tests/test_travel_details.py

Fix finance export

---

EquiTrack/t2f/templates/emails/certificate_submitted.html
EquiTrack/t2f/templates/emails/certified.html

fixes unicef/etools-issues#413

Fix mail templates

---

EquiTrack/t2f/models.py
EquiTrack/t2f/tests/test_action_points.py

Fix action point mailing

---

EquiTrack/t2f/serializers/travel.py
EquiTrack/t2f/tests/test_dashboard.py

fixes unicef/etools-issues#231

Add trip_id to activities list

---

EquiTrack/partners/tests/test_views.py
EquiTrack/partners/urls_v2.py
EquiTrack/partners/views/partner_organization_v2.py

fixes unicef/etools-issues#367

add partner delete endpoint

---

EquiTrack/EquiTrack/factories.py
EquiTrack/funds/serializers.py
EquiTrack/funds/tests/test_views.py

Tests added
Fixes: unicef/etools-issues#498

add star, end dates to Fr serializer

---

EquiTrack/partners/admin.py
EquiTrack/partners/serializers/partner_organization_v2.py
EquiTrack/partners/tests/test_views.py

fixes unicef/etools-issues#366

Partner show hidden field in admin

---

docs/guidelines.rst

Small updates to guidelines

---

EquiTrack/assets/partner/intervention_permissions.csv

Fix misspelling of result_links

Permission matrix tweak

---

EquiTrack/.flake8
EquiTrack/publics/admin.py
EquiTrack/publics/management/commands/load_initial_data.py
EquiTrack/publics/tasks.py
EquiTrack/publics/tests/factories.py
EquiTrack/publics/tests/test_dsa_rates.py
EquiTrack/publics/tests/test_ghost_data.py
EquiTrack/publics/views.py

This PR fixes flake8 errors and adjusts imports.
Issues identified for future cleanup:
* models.py: Docstrings
* serializers.py: Address TODOs
* tasks.py: Use 'logger' instead of 'log'
* tasks.py: Docstrings and comments
* views.py: Docstrings
* test_static_data_endpoints: could use FactoryBoy create_batch
* Add tests

Clean up publics app

---

circle.yml

This is an attempt to speed up CI builds for feature branches, but keep the ability to run tests in the docker container for deployable branches.

Speed up feature branch CI

---

EquiTrack/audit/views.py
EquiTrack/vision/adapters/manual.py
EquiTrack/vision/adapters/purchase_order.py
EquiTrack/vision/vision_data_synchronizer.py

- Allowed custom dataloader in vision synchronizer. 
- Fixed PO synchronizer by using correct url for fetching data.

PO Synchronizer fix for manual update.

---

EquiTrack/EquiTrack/tests/test_all_models.py

improve the test that examines all models for Python 3-compatible `__str__()` and `__unicode__()` methods. The previous version of this code didn't handle models that did implement neither `__str__()` nor `__unicode__()`. It was sufficient for the funds and locations apps, but not for partners.
I expanded the test to understand all 5 different categories of models that it can encounter. (See code for detailed comments.)
In addition to improving the guts, I removed funds and location from the `EXCLUDED_PACKAGES` list. They are now Python 3-compatible and protected from slippage by this function.

improve the test that examines all models for Python 3-compatiblity

---

EquiTrack/reports/models.py

Fix lower result unique code generation when older records are deleted from the table
connects unicef/etools-issues#782

Fix lower result unique code generation

---

EquiTrack/templates/partners/pca/english_pdf.html

Work on the english template.
Connects unicef/etools-issues#678

Fix text formatting issues of the PCA templates

---

EquiTrack/users/serializers.py
EquiTrack/users/tests/test_views.py

implements workspace api changes from https://github.com/unicef/etools/issues/934 and a (very) simple test for good measure.

Workspace api additions

---

EquiTrack/partners/serializers/interventions_v2.py
EquiTrack/partners/tests/test_views.py

connects unicef/etools-issues#832

Add primary key to the interventionreportingperiod serializer

---

EquiTrack/management/tasks.py

sorry about that. I must not have actually ever tried running the tasks

fix import issue on tasks

---

EquiTrack/partners/models.py
EquiTrack/partners/tests/test_models.py

Removed unused logic, last_audit was being set but not used.

Update audit_needed method on PartnerOrganization

---

EquiTrack/EquiTrack/data/audit_staff_organization.json

Removed nonexistent and unnecessary fields from audit_staff_organization fixture.

Auditor portal fix

---

EquiTrack/EquiTrack/factories.py
EquiTrack/partners/models.py
EquiTrack/partners/tests/test_models.py

Year value passed to TravelActivity queryset count was invalid

Fix spot_checks method

---

EquiTrack/users/admin.py
EquiTrack/users/apps.py
EquiTrack/users/forms.py
EquiTrack/users/models.py
EquiTrack/users/serializers.py
EquiTrack/users/serializers_v3.py
EquiTrack/users/tasks.py
EquiTrack/users/tests/test_csrf.py
EquiTrack/users/tests/test_models.py
EquiTrack/users/tests/test_views.py
EquiTrack/users/urls.py
EquiTrack/users/urls_v2.py
EquiTrack/users/urls_v3.py
EquiTrack/users/views.py
EquiTrack/users/views_v3.py

- 1. print py3 compatible
- 2. used user_model
- 3. pep8
- 4. flake8
- 5. isort

tweaked users app

---

EquiTrack/partners/models.py
EquiTrack/partners/serializers/dashboards.py
EquiTrack/partners/views/dashboards.py
EquiTrack/partners/views/partner_organization_v2.py

fixes unicef/etools-issues#867
fixes unicef/etools-issues#843

Dashboard Fixes

---

EquiTrack/setup.cfg
setup.cfg

maybe we can include .flake8 content here as well

added setup.cfg

---

EquiTrack/partners/templatetags/userprofile_tags.py
EquiTrack/templates/admin/index.html

hide tenant apps for global schema
hide global country if in tenant model

handle tenant models in admin site

---

EquiTrack/partners/models.py
EquiTrack/partners/tests/test_models.py

`days_from_submission_to_signed` and `days_from_review_to_signed` affected

Fix relativedelta usage

---

EquiTrack/EquiTrack/settings/base.py
EquiTrack/requirements/base.txt

Connects unicef/etools-issues#172

Remove djrill (unused)

---

EquiTrack/t2f/serializers/export.py
EquiTrack/t2f/tests/test_exports.py
EquiTrack/t2f/views/exports.py

connects unicef/etools-issues#887

changed fields on export for travel activities

---

EquiTrack/environment/models.py
EquiTrack/environment/tests/factories.py
EquiTrack/environment/tests/test_models.py
EquiTrack/environment/tests/test_views.py
docs/feature-flags.rst
docs/index.rst

Add tests and docs for feature-flags

---

EquiTrack/monitoring/tests/test_checks.py
EquiTrack/monitoring/tests/test_views.py
EquiTrack/monitoring/urls.py

Increate test coverage in monitoring app
See https://github.com/unicef/etools-issues/issues/1104

Add monitoring tests

---

EquiTrack/assets/partner/intervention_permissions.csv
EquiTrack/partners/models.py
EquiTrack/partners/permissions.py
EquiTrack/partners/tests/test_api_interventions.py

fixes: unicef/etools-issues#1101 
fixes: unicef/etools-issues#1043
fixes: unicef/etools-issues#1074
More tests needed.

Fix section validator

---

EquiTrack/t2f/templates/emails/approved.html
EquiTrack/t2f/templates/emails/submit_for_approval.html

connects unicef/etools-issues#971

removed cost fields from email confirmations 

---

EquiTrack/partners/models.py
EquiTrack/partners/serializers/interventions_v2.py
EquiTrack/partners/tests/test_api_interventions.py
EquiTrack/partners/views/interventions_v2.py

Attempt to optimize the intervention list api endpoint

Optimize intervention list

---

EquiTrack/EquiTrack/settings/base.py

this is needed to run celery 4.
in the yml file we need to add -A EquiTrack and run celery instead of python manage.py celery

added CELERY_ACCEPT_CONTENT

---

EquiTrack/hact/models.py
EquiTrack/partners/serializers/partner_organization_v2.py
EquiTrack/partners/tests/test_serializers.py
EquiTrack/partners/views/partner_organization_v2.py

removed partner from PartnerEngagement serializer
efficent query

performance and fixed chart labels

---

.circleci/config.yml

Reverts unicef/etools#1240
Throwing errors when testing on other branches randomly... weird

Revert "CI: less aggressive cache-busting"

---

EquiTrack/snapshot/tests/test_utils.py
EquiTrack/snapshot/utils.py

[ch4792]
Snapshot jsonify function has issues dealing with queryset objects

Handle queryset lists in snapshot jsonify

---

EquiTrack/attachments/serializers.py
EquiTrack/attachments/views.py
EquiTrack/audit/serializers/export.py
EquiTrack/audit/tests/test_views.py

[ch4981]
Fix issue with special audit exports when attachments involved

Issue special audit attachment

---

EquiTrack/EquiTrack/mixins.py
EquiTrack/funds/serializer_exports.py
EquiTrack/partners/serializers/exports/agreements.py
EquiTrack/partners/serializers/exports/interventions.py
EquiTrack/partners/serializers/exports/partner_organization.py
EquiTrack/partners/tests/test_export_partner.py
EquiTrack/reports/serializers/exports.py

[ch4383]
Add country (schema_name) column to all flat exports.
Exports are still limited by workspace, being able to export all workspace will be handled once we have a data warehouse in place.

Add country to flat exports

---

EquiTrack/partners/serializers/dashboards.py
EquiTrack/partners/views/dashboards.py

Attempting to minimize the files affected in correctly the issue.
This has slower performance compared to https://github.com/unicef/etools/pull/1330

Fix InterventionPartnershipDashView query

---

.circleci/config.yml
.circleci/images/primary/Dockerfile

Maybe this is a better way to fix the CI build&deploy task.

Circleci build changes - cleaned up

---

EquiTrack/reports/serializers/exports.py

fix pd result export forgot to return ram indicators

---

EquiTrack/EquiTrack/settings/base.py
EquiTrack/EquiTrack/settings/local.py
EquiTrack/EquiTrack/urls.py
EquiTrack/audit/urls.py
EquiTrack/environment/urls_v2.py
EquiTrack/funds/urls.py
EquiTrack/hact/urls.py
EquiTrack/partners/prp_urls.py
EquiTrack/partners/urls_v2.py
EquiTrack/partners/views/interventions_v2.py
EquiTrack/publics/urls.py
EquiTrack/snapshot/urls.py
EquiTrack/t2f/views/exports.py
EquiTrack/users/tests/test_tasks.py
EquiTrack/users/tests/test_views.py
EquiTrack/users/urls.py
EquiTrack/users/urls_v2.py
EquiTrack/users/urls_v3.py
EquiTrack/users/views.py
EquiTrack/utils/common/urlresolvers.py
EquiTrack/utils/writable_serializers/tests/models.py

These are changing required by django 1.11 (and 2.0), compatible with current 1.10.
In order to keep the pr https://github.com/unicef/etools/pull/1207 light (few files) while we wait django-tenant-schema to be ready.

toward django 1.11 [ch396]

---

EquiTrack/t2f/views/exports.py

t2f added filter for location [ch5381]

---

EquiTrack/EquiTrack/middleware.py
EquiTrack/environment/models.py
EquiTrack/locations/views.py
EquiTrack/partners/permissions.py

removed is authenticated warnings [ch396]

---

EquiTrack/attachments/serializers.py
EquiTrack/audit/management/commands/update_audit_permissions.py
EquiTrack/audit/serializers/engagement.py
EquiTrack/audit/serializers/export.py
EquiTrack/audit/templates/audit/audit_pdf.html
EquiTrack/audit/templates/audit/engagement_pdf.html
EquiTrack/audit/tests/test_views.py
EquiTrack/audit/views.py
EquiTrack/firms/models.py
EquiTrack/notification/management/commands/update_notifications.py
EquiTrack/tpm/export/serializers.py
EquiTrack/utils/common/models/mixins.py
EquiTrack/utils/common/serializers/fields.py
EquiTrack/utils/common/views.py

PR to master, as suggested @ntrncic in https://github.com/unicef/etools/pull/1446

Auditor portal updates [Master]

---

src/etools/applications/partners/tasks.py
src/etools/applications/users/tasks.py

improved pmp report [ch5638]

---

.pyup.yml

More configuration options available here: https://pyup.io/docs/bot/config/
This config turns off automated PRs whenever a requirement has a new release, but turns on checks of each PR for security vulnerabilities.

A starting config for pyup.io

---

src/etools/applications/tpm/export/renderers.py
src/etools/applications/tpm/export/serializers.py
src/etools/applications/tpm/management/commands/update_tpm_permissions.py
src/etools/applications/tpm/models.py

temporary changes for two trello cards
https://trello.com/c/Nhi0M7e5/161-assignee-of-action-point-is-unable-to-edit-the-action-point
https://trello.com/c/FJirC8ou/163-please-add-description-and-id-as-a-column-to-the-list-view-action-point-export
to achieve required behavior with old action points model

[STAGING] [TPM] Action points changes to export & permissions

---

src/etools/applications/partners/__init__.py
src/etools/applications/partners/apps.py
src/etools/applications/partners/models.py
src/etools/applications/partners/serializers/exports/interventions.py
src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/signals.py
src/etools/applications/partners/tests/test_models.py
src/etools/applications/partners/views/interventions_v2.py
src/etools/applications/reports/__init__.py
src/etools/applications/reports/apps.py
src/etools/applications/reports/models.py
src/etools/applications/reports/signals.py

[ch6233]
Added caching on locations, sections, and clusters, in an attempt to increase endpoint performance.

Performance improvement for intervention maps endpoint

---

src/etools/applications/attachments/serializers.py
src/etools/applications/tpm/tests/test_models.py
src/etools/applications/tpm/views.py

updated attachments serializer according to feedback in https://github.com/unicef/etools/pull/1658

[Audit/TPM] Multipart attachments improvement

---

src/etools/applications/audit/serializers/engagement.py
src/etools/applications/audit/tests/test_views.py
src/etools/applications/audit/views.py
src/etools/applications/tpm/tests/test_views.py
src/etools/applications/tpm/views.py
src/etools/applications/users/views.py

fixed https://trello.com/c/IzCqL3g0/168-bug-500-error-relatedobjectdoesnotexist-when-calling-api-tpm-visits-pk

Audit & TPM fixes

---

src/etools/applications/management/serializers.py
src/etools/applications/management/tests/test_views.py

add parent_id to the geojson output

---

src/etools/applications/audit/serializers/export.py
src/etools/applications/audit/serializers/risks.py
src/etools/applications/utils/common/serializers/fields.py
src/etools/applications/utils/common/utils.py

removed DynamicChoicesField in favor to standard ChoiceField.

DynamicChoicesField fix

---

src/etools/applications/partners/exports_v2.py

[ch5397] fixed hact export

---

.gitignore
src/etools/applications/t2f/serializers/travel.py
src/etools/applications/t2f/tests/test_dashboard.py

[ch6335] traveler latest date

---

src/etools/applications/partners/models.py
src/etools/applications/partners/serializers/exports/interventions.py
src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
src/etools/applications/partners/tests/test_api_interventions.py

Add internal_prc_review attachment to InterventionAmendment

---

src/etools/applications/users/admin.py
src/etools/applications/users/tasks.py

fixed user create (need to be staff)

fixed user admin

---

src/etools/applications/partners/permissions.py
src/etools/assets/partner/agreement_permissions.csv

[ch1511] agreement permissions changed for authorized_officers

---

src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/views/interventions_v2.py

[ch5968] fixed InterventionListMapView

---

src/etools/applications/reports/views/v2.py

fix export

---

src/etools/applications/attachments/management/commands/update_attachment_source.py

[ch6859]
Add django command that updates source value for current attachment flat records
`python manage.py update_attachment_source`

Add update_attachment_source command

---

src/etools/applications/partners/serializers/exports/interventions.py

[ch7346] fixed export (DRF 3.8)

---

src/etools/applications/partners/admin.py

[ch7501] fixed intervention amendment admin

---

src/etools/applications/partners/views/dashboards.py

[ch7300] partnership dashboard api filterable by pk

---

src/etools/applications/t2f/serializers/export.py
src/etools/applications/t2f/tests/test_exports.py
src/etools/applications/t2f/views/exports.py

adds supervisor to travel export

---

src/etools/applications/partners/synchronizers.py

[ch7694] fixed core value assessment creation for new partner

---

src/etools/applications/action_points/export/serializers.py

with "allow_null" we don't need this anymore (coming from staging hotfix)

remove useless methods

---

src/etools/applications/t2f/serializers/travel.py

[ch7823] fixed travel serializer

---

src/etools/applications/partners/models.py

[ch7593] fixed active partner criteria

---

src/etools/applications/audit/filters.py
src/etools/applications/audit/views.py
src/etools/applications/tpm/views.py

[ch7616] tpm visits and engagments multiple select filter

---

src/etools/applications/hact/models.py
src/etools/applications/hact/tests/test_models.py
src/etools/applications/t2f/tests/test_travel_details.py

[ch7024] fixed staff spot checks

---

src/etools/applications/audit/purchase_order/admin.py
src/etools/applications/audit/views.py

[ch7567] allow to filter auditor staff member by workspace

---

src/etools/applications/audit/views.py
src/etools/applications/tpm/signals.py
src/etools/applications/users/models.py
src/etools/applications/users/tests/test_models.py

[ch7569] Deactivate only not unicef users

---

src/etools/applications/partners/tasks.py

Update pd email notification

---

src/etools/applications/audit/admin.py

[ch8127] sentry-staging-675475485: fixed admin filter

---

src/etools/applications/audit/purchase_order/models.py

[ch7895] purchase order str method

---

src/etools/applications/audit/serializers/engagement.py

[ch7489] Engagement removed id from export

---

src/requirements/base.txt
src/requirements/input/base.in
src/requirements/test.txt

[ch8162] old sdk: upgrade sentry

---

src/etools/applications/partners/admin.py
src/etools/applications/partners/validation/agreements.py

SSFA Header not move to signed and add year to admin

---

src/etools/applications/partners/views/partner_organization_v2.py

[ch8169] ip_dashboard pca required alert

---

src/etools/applications/reports/views/v2.py

[ch8114] fixed_applied_indicator_export

---

src/etools/applications/firms/serializers.py
src/etools/applications/users/models.py

[ch8232] tpm visit list view added full name to focal point

---

src/etools/applications/publics/models.py

[ch7840] softdeletemixin allow force delete

---

src/etools/applications/partners/models.py
src/etools/applications/partners/views/partner_organization_v2.py

[ch8169] fixed ip dashboard alert

---

src/etools/applications/action_points/export/renderers.py

[ch8381] changed export column name

---

src/etools/applications/tpm/filters.py

[ch7560] TPM: allow to filter by date

---

src/etools/assets/partner/intervention_permissions.csv

[ch8270] permission matrix: allow to change unicef_signatory in Signed Status

---

src/etools/applications/tpm/management/commands/update_tpm_permissions.py

[ch8251] update tpm permission matrix

---

src/etools/applications/action_points/export/renderers.py
src/etools/applications/action_points/export/serializers.py

[ch8567] ADP: export added high priority

---

src/etools/applications/users/tasks.py
src/etools/config/settings/base.py
src/etools/libraries/azure_graph_api/tasks.py

[ch8647] user sync: fixed user without profile + changed celery queue

---

src/etools/applications/partners/notifications/agreement-suspended.py
src/etools/applications/partners/tests/test_views.py
src/etools/applications/partners/utils.py
src/etools/applications/partners/views/agreements_v2.py

Send suspension notification when agreement suspended

---

src/etools/applications/action_points/export/serializers.py

[ch8820] ap export fixed none value for str

---

.gitignore
src/etools/applications/action_points/export/renderers.py

[ch8808] ap export fixed action

---

src/etools/applications/attachments/management/commands/denormalize_attachments.py

All `--all` flag to be passed to `denormalize_attachment` command, so all attachments are procssed

Denormalize attachments all flag

---

src/etools/applications/reports/models.py
src/etools/applications/reports/views/v2.py

[ch8116] export applied indicators

---

src/etools/applications/reports/models.py

[ch8116] pd result export fix

---

src/etools/applications/partners/serializers/exports/interventions.py
src/etools/applications/partners/tests/test_export_intervention.py

Add cso_type field to intervention export

---

src/etools/applications/partners/tests/test_views.py
src/etools/applications/partners/views/partner_organization_v2.py

Update Partner Dashboard view queryset to handle filtering/searching

---

src/etools/applications/hact/models.py
src/etools/applications/hact/tests/test_models.py

[ch8797] hact dashboard: added outstanding previous year

---

src/etools/applications/partners/views/dashboards.py

[ch1907] new my dashboard

---

src/etools/applications/hact/models.py
src/etools/applications/hact/renderers.py
src/etools/applications/hact/tests/test_models.py
src/etools/applications/hact/urls.py
src/etools/applications/hact/views.py

[ch8793] freeze hact charts

---

src/etools/applications/partners/serializers/partner_organization_v2.py

Add partner_type field to partner dashboard payload

---

src/etools/applications/publics/admin.py
src/etools/applications/publics/models.py
src/etools/applications/publics/serializers.py
src/etools/applications/publics/synchronizers.py
src/etools/applications/publics/views.py

py3 super syntax - Publics app

---

src/etools/applications/firms/serializers.py

py3 super syntax - Firms app

---

src/etools/applications/action_points/serializers.py
src/etools/applications/action_points/tests/base.py
src/etools/applications/action_points/tests/factories.py
src/etools/applications/action_points/tests/test_transitions.py
src/etools/applications/action_points/tests/test_views.py
src/etools/applications/action_points/transitions/conditions.py

py3 super syntax - Action points app

---

src/etools/applications/attachments/models.py

py3 super syntax - Attachments app

---

src/etools/applications/environment/models.py

py3 super syntax - Env app

---

src/etools/applications/permissions2/metadata.py
src/etools/applications/permissions2/serializers.py
src/etools/applications/permissions2/tests/mixins.py
src/etools/applications/permissions2/views.py

py3 super syntax - Permissions app

---

src/etools/applications/audit/exports.py
src/etools/applications/audit/models.py
src/etools/applications/audit/purchase_order/synchronizers.py
src/etools/applications/audit/serializers/auditor.py
src/etools/applications/audit/serializers/engagement.py
src/etools/applications/audit/serializers/mixins.py
src/etools/applications/audit/serializers/risks.py
src/etools/applications/audit/tests/base.py
src/etools/applications/audit/tests/test_email.py
src/etools/applications/audit/tests/test_transitions.py
src/etools/applications/audit/tests/test_views.py
src/etools/applications/audit/transitions/conditions.py
src/etools/applications/audit/views.py

py3 super syntax - Audit app

---

src/etools/applications/funds/models.py
src/etools/applications/funds/synchronizers.py
src/etools/applications/funds/tests/test_api.py
src/etools/applications/funds/views.py

py3 super syntax - Funds app

---

src/etools/applications/activities/serializers.py

py3 super syntax - Activitites app

---

src/etools/applications/tpm/models.py
src/etools/applications/tpm/serializers/attachments.py
src/etools/applications/tpm/serializers/visit.py
src/etools/applications/tpm/tests/factories.py
src/etools/applications/tpm/tests/test_transitions.py
src/etools/applications/tpm/tests/test_views.py
src/etools/applications/tpm/tpmpartners/synchronizers.py
src/etools/applications/tpm/views.py

py3 super syntax - TPM app

---

src/etools/applications/t2f/filters/travel_list.py
src/etools/applications/t2f/helpers/permission_matrix.py
src/etools/applications/t2f/html_views.py
src/etools/applications/t2f/models.py
src/etools/applications/t2f/serializers/__init__.py
src/etools/applications/t2f/serializers/export.py
src/etools/applications/t2f/serializers/filters/__init__.py
src/etools/applications/t2f/serializers/filters/travel_list.py
src/etools/applications/t2f/serializers/invoices.py
src/etools/applications/t2f/serializers/travel.py
src/etools/applications/t2f/tests/test_dsa_calculations.py
src/etools/applications/t2f/tests/test_invoice_making.py
src/etools/applications/t2f/tests/test_travel_details.py
src/etools/applications/t2f/views/exports.py
src/etools/applications/t2f/views/travel.py

py3 super syntax - T2F app

---

src/etools/applications/utils/common/models/mixins.py
src/etools/applications/utils/common/schemas.py
src/etools/applications/utils/common/tests/factories.py
src/etools/applications/utils/sentry/client.py

py3 super syntax - utils app

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/get__api_v2_interventions_amendments_.response.json
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/tests/test_export_intervention.py

[ch9001]
Updated a test to ensure that attachment is denormalized correctly

Update prc review interview payload name to match what front end uses

---

src/etools/applications/partners/views/partner_organization_v2.py

[ch9073] partner dashboard: fixed alert

---

src/etools/applications/partners/views/partner_organization_v2.py

[ch9073] alert final fix

---

src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/publics/tests/test_ghost_data.py
src/requirements/base.txt
src/requirements/input/base.in
src/requirements/test.txt

[ch8917] djangorestframework 39

---

src/etools/applications/users/templates/admin/users/country/change_form.html

[ch9293] tweak country admin

---

src/etools/applications/field_monitoring/planning/export/renderers.py
src/etools/applications/field_monitoring/planning/export/serializers.py
src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/field_monitoring/planning/views.py

[Field monitoring] csv exports for planning

---

src/etools/applications/EquiTrack/auth.py
src/etools/config/settings/base.py

Revert "Prp refactoring auth poc2"

---

src/etools/applications/t2f/serializers/static_data.py
src/etools/applications/t2f/tests/test_static_data_endpoint.py
src/etools/applications/t2f/views/generics.py

[ch9147] remove partnership from static

---

src/etools/applications/attachments/models.py
src/etools/applications/attachments/tests/test_models.py
src/etools/applications/attachments/tests/test_utils.py
src/etools/applications/attachments/utils.py

Set the source for trips attachments to "Trips" and exclude from document library

Exclude Trips from document library

---

src/etools/applications/audit/notifications/staff_member-invite.py
src/etools/applications/audit/purchase_order/models.py
src/etools/applications/firms/utils.py
src/etools/applications/permissions2/views.py
src/etools/applications/tpm/models.py
src/etools/applications/utils/common/tests/test_utils.py
src/etools/applications/utils/common/urlresolvers.py

[ch9486] email with social auth - change email link

---

src/etools/applications/t2f/serializers/export.py
src/etools/applications/t2f/tests/test_exports.py

Fix type filter in hact_visit_report field

---

src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_api_partners.py

[ch7188]
There appears to be minimal performance impact by this change.

Update intervention frs calculation query, handle non distinct values

---

src/etools/applications/audit/views.py

[ch9364] staff spot checks export: rename export file name

---

Pipfile
Pipfile.lock
src/etools/applications/action_points/export/renderers.py
src/etools/applications/action_points/export/serializers.py

[ch9019] alternative

---

src/etools/applications/audit/serializers/attachments.py
src/etools/applications/audit/tests/test_attachment_link_views.py
src/etools/applications/audit/tests/test_views.py
src/etools/applications/audit/urls.py
src/etools/applications/audit/views.py

Added endpoints to be able to add attachments as links to the audit engagement models

Engagement attachment links

---

src/etools/templates/partners/pca/french_pdf.html
src/etools/templates/partners/pca/portuguese_pdf.html
src/etools/templates/partners/pca/spanish_pdf.html

modified:   src/etools/templates/partners/pca/french_pdf.html
modified:   src/etools/templates/partners/pca/portuguese_pdf.html
modified:   src/etools/templates/partners/pca/spanish_pdf.html

Hotfix for PCA templates staging

---

src/etools/templates/partners/pca/ifrc_english_pdf.html

Minor typo fixes

---

src/etools/applications/audit/transitions/conditions.py

[ch9676] remove total_amount_of_ineligible_expenditure has mandatory field

---

src/etools/templates/partners/pca/english_pdf.html
src/etools/templates/partners/pca/french_pdf.html
src/etools/templates/partners/pca/ifrc_english_pdf.html
src/etools/templates/partners/pca/ifrc_french_pdf.html
src/etools/templates/partners/pca/spanish_pdf.html

[CH7894] PCA templates typo fixes

---

src/etools/applications/action_points/tests/factories.py
src/etools/applications/action_points/tests/test_emails.py
src/etools/applications/action_points/tests/test_models.py
src/etools/applications/action_points/tests/test_transitions.py
src/etools/applications/action_points/tests/test_views.py
src/etools/applications/audit/tests/base.py
src/etools/applications/audit/tests/factories.py
src/etools/applications/audit/tests/test_email.py
src/etools/applications/audit/tests/test_views.py
src/etools/applications/tpm/tests/base.py
src/etools/applications/tpm/tests/factories.py
src/etools/applications/tpm/tests/test_email.py
src/etools/applications/tpm/tests/test_transitions.py
src/etools/applications/tpm/tests/test_views.py
src/etools/applications/users/tests/factories.py
src/etools/applications/utils/common/tests/factories.py

added metaclass to avoid importing tons of factories for every instance status

Fix broken deep attributes in traits after factory-boy upgrade

---

src/etools/applications/audit/models.py
src/etools/applications/audit/utils.py

[ch8263]
Proper use of django File field, as well and tempfile.
Fixes the following issues;
- https://sentry.io/share/issue/bdc3bee883e64785bc512dbe77a8b950/
- https://sentry.io/share/issue/8186b88f32c443cabe8545ae007f7943/

Fix issues generating final report

---

src/etools/applications/partners/admin.py

Correct InterventionAttachment admin handling

---

src/etools/applications/partners/admin.py
src/etools/applications/partners/forms.py

Override attachment field value in InterventionAttachmentInline

---

src/etools/applications/audit/tests/test_transitions.py
src/etools/applications/audit/utils.py

Ensure file type created properly, with label

Update way generated file is saved

---

src/etools/applications/partners/tasks.py
src/etools/applications/partners/tests/test_tasks.py

Don't prepend to settings.HOST for email links

---

src/etools/applications/t2f/models.py

Add check_trip_dates condition to mark_as_completed transition

---

src/etools/applications/reports/serializers/v2.py
src/etools/applications/reports/tests/test_validators.py
src/etools/applications/reports/validators.py

Baseline allow none

---

src/etools/applications/audit/views.py

[ch10282] fam allow filter staff members with countries available

---

src/etools/config/settings/base.py
src/etools/libraries/monitoring/service_checks.py
src/etools/libraries/monitoring/tests/test_checks.py
src/etools/libraries/monitoring/tests/test_views.py
src/etools/libraries/monitoring/urls.py
src/etools/libraries/monitoring/views.py

[ch10192] readiness API

---

src/etools/applications/t2f/serializers/travel.py

Issue was that a date field was attempting to be serialized as a datetime field

Fix failing dev tests

---

src/etools/applications/tpm/views.py

[ch10666] tpm filtering export

---

src/etools/applications/action_points/views.py

Update action point export renderer format

---

src/etools/applications/tpm/export/renderers.py
src/etools/applications/tpm/export/serializers.py

[ch10459] tpm export amend

---

src/etools/applications/reports/renderers.py
src/etools/applications/reports/serializers/v2.py
src/etools/applications/reports/tests/test_views.py
src/etools/applications/reports/views/v2.py

[ch10174]
Make use of baseline, target from applied indicators

Update result framework serializer 

---

src/etools/applications/management/templates/portal.html
src/etools/applications/management/urls.py
src/etools/applications/management/views/tasks_endpoints.py

added purge queue
added sync all users
[ch11233]

[ch11233] Management App tweaks

---

src/etools/applications/partners/views/agreements_v2.py

[ch11123] agreement export fix

---

src/etools/applications/t2f/serializers/export.py
src/etools/applications/t2f/tests/test_exports.py

[ch11066] t2f: added purpose to export

---

README.rst

[ch1046] update README

---

src/etools/config/settings/base.py
src/etools/libraries/social_django/middleware.py

Add SocialAuthException middleware

---

src/etools/applications/publics/admin.py
src/etools/applications/t2f/admin.py
src/etools/applications/tpm/admin.py
src/etools/libraries/djangolib/admin.py

AdminListMixin in djangolib package

moved AdminListMixin

---

src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_models.py

[ch11851] hact count for spot checks and audit

---

src/etools/applications/audit/signals.py
src/etools/applications/audit/tests/test_models.py
src/etools/applications/tpm/signals.py
src/etools/applications/tpm/tests/test_models.py
src/etools/applications/vision/tasks.py

[ch11981] remove signal external partner

---

src/etools/applications/action_points/export/serializers.py

Correct ref_link value in action points export

---

src/etools/applications/attachments/management/commands/init-attachment-file-types.py
src/etools/applications/users/management/commands/add_country.py

[ch12439]
New countries need to be initialized with this command that sets up relevant attachment `FileType` label, and name values

Add init command to initialize attachment file types for new country

---

src/etools/applications/t2f/helpers/permission_matrix.py

[ch12396]
Report permissions are limited to just model level

t2f report permission

---

src/etools/applications/attachments/management/commands/init-attachment-file-types.py

Use update_or_create and not get_or_create for init attachment filetypes

---

src/etools/applications/audit/management/commands/update_audit_permissions.py

[ch12815] allow to see reports for any status

---

src/etools/applications/hact/models.py
src/etools/applications/hact/tests/test_models.py

[ch12811] hact more fixes

---

src/etools/applications/audit/management/commands/update_audit_permissions.py

[ch12682] FAM attchment permissions

---

src/etools/applications/firms/serializers.py
src/etools/libraries/djangolib/tests/test_validators.py
src/etools/libraries/djangolib/validators.py

[ch12015] forbid uppercase chars when adding email

---

src/etools/applications/partners/serializers/partner_organization_v2.py
src/etools/applications/partners/tests/test_views.py
src/etools/applications/partners/views/partner_organization_v2.py

[ch12242] partner dashboard core values assess date

---

src/etools/applications/partners/views/interventions_v2.py
src/etools/applications/reports/views/v2.py

[ch12424] intervention filter by partner/agreement

---

src/etools/applications/partners/templates/pca/french_pdf.html

[Ch13098] Fix french PCA document issues

---

src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_models.py

[ch12873] hact spot check required

---

src/etools/applications/partners/tests/test_views.py
src/etools/applications/partners/urls_v2.py
src/etools/applications/partners/views/interventions_v2.py

[CH11545] Add endpoint for intervention PV deletion in draft status

---

src/etools/applications/attachments/management/commands/remove_pd_pca_doc_types.py
src/etools/applications/attachments/tests/test_commands.py

Copied code from migration to django command

Remove pd pca doc types

---

src/etools/applications/partners/models.py

[ch12873] fix spot_check_required

---

src/etools/applications/audit/management/commands/update_audit_permissions.py

[ch13273] ament permissions

---

src/etools/applications/partners/templates/pca/french_pdf.html
src/etools/applications/partners/templates/pca/ifrc_french_pdf.html

- few more fixes in the 'French' and 'IFRC French' PCA templates

French PCA template quickfix

---

src/etools/applications/tpm/management/commands/update_tpm_permissions.py
src/etools/applications/tpm/tests/test_transitions.py

[ch10175] tpm approve permission

---

src/etools/applications/tpm/export/renderers.py
src/etools/applications/tpm/export/serializers.py

[ch13377] tpm activity is_pv export

---

src/etools/applications/hact/models.py
src/etools/applications/hact/tests/test_models.py

[ch12877] hact dashboard spot checks: change MR to required

---

src/etools/applications/audit/filters.py

[ch9465] engagement allow to filter by partner_contacted_at date

---

src/etools/applications/funds/synchronizers.py
src/etools/applications/funds/tests/test_views.py
src/etools/applications/funds/tests/vcr_cassettes/fund_reservation_invalid.yml
src/etools/applications/funds/views.py
src/etools/applications/vision/exceptions.py

[ch13710] FR random issue

---

src/etools/applications/partners/synchronizers.py
src/etools/applications/partners/tests/test_api_partners.py
src/etools/applications/partners/views/partner_organization_v2.py

[Ch12698] Fix partner import keyerror when 'partner_type_desc' is missing

---

src/etools/applications/partners/serializers/prp_v1.py
src/etools/applications/partners/tests/data/prp-intervention-list.json
src/etools/applications/partners/views/prp_v1.py

[ch13413] PRP API: Intervention added type

---

src/etools/applications/psea/models.py
src/etools/applications/psea/permission_matrix/assessment_permissions.csv
src/etools/applications/psea/serializers.py
src/etools/applications/psea/tests/test_models.py
src/etools/applications/psea/tests/test_views.py
src/etools/applications/psea/views.py

Changes;
Update overall rating calculation, all answers need to be completed first
Permission added around overall rating for submitted and final status
Added validation that user in Focal Group when adding

PSEA Module

---

src/etools/applications/core/data/attachments_file_types.json
src/etools/applications/core/data/psea_indicators.json
src/etools/applications/psea/models.py
src/etools/applications/psea/serializers.py
src/etools/applications/psea/validation.py

fix display rating and validation messages

---

src/etools/applications/psea/serializers.py

Add user_details to Assessor serializer

---

src/etools/applications/audit/management/commands/update_audit_permissions.py

[ch15278] update auditor permissions

---

src/etools/applications/psea/tests/test_views.py
src/etools/applications/psea/validation.py

Require staff members set when assigning if assessor is vendor type

---

src/etools/applications/core/util_scripts.py
src/etools/applications/management/handlers/sections.py
src/etools/applications/management/tests/handlers/test_sections.py
src/etools/applications/management/views/sections.py

- tweak section management (no need to specify type or relationship)
- catching MigrationException Issue throwing 400
- moved section management
- set_country accept also short_code and schema_name

Management section tweaks

---

src/etools/applications/vision/tests/test_tasks.py

celery settings changed in celery 4

tests: changed setting celery

---

src/etools/applications/audit/serializers/engagement.py

[ch12675] currency mandatory

---

src/etools/applications/partners/migrations/0037_auto_20190502_1407.py

we get an error when running `add_country` command
```
[1/1 (100%) standard:lesotho]  OK
[1/1 (100%) standard:lesotho]   Applying partners.0036_auto_20190418_1832...
[1/1 (100%) standard:lesotho]  OK
[1/1 (100%) standard:lesotho]   Applying partners.0037_auto_20190502_1407...
CommandError: No installed app with label 'unicef_attachments'.
```

clean datamigration

---

src/etools/applications/psea/notifications/assessment-assigned.py
src/etools/applications/psea/notifications/assessment-final.py
src/etools/applications/psea/notifications/assessment-submitted.py

Update PSEA notification content

---

src/etools/applications/action_points/signals.py

Update action point signals to handle psea assessment email

---

src/etools/applications/psea/permission_matrix/assessment_permissions.csv
src/etools/applications/psea/permissions.py
src/etools/applications/psea/tests/test_views.py

[ch15531]
Assessors only can edit answers

Update psea answer permissions

---

src/etools/applications/psea/models.py

[ch15940] fix PSEA frontend url

---

src/etools/applications/psea/serializers.py
src/etools/applications/psea/tests/test_serializers.py

Update PSEA overall rating calculation

---

src/etools/applications/users/serializers_v3.py
src/etools/applications/users/tests/test_views_v3.py

Add external user to Auditor group

---

src/etools/applications/psea/serializers.py
src/etools/applications/psea/tests/test_serializers.py
src/etools/applications/psea/validators.py

Add psea assessment date validation

---

Pipfile
Pipfile.lock
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPICartoDB/get__locations_cartodbtables__None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations-light__None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations-types__None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations_101__None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations__None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__api_locations_pcode_abc__None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/get__locations_autocomplete__None.response.json
src/etools/libraries/locations/tests/test_views.py

[ch15331]
Update locations-light view test

Update unicef-locations to 1.8

---

src/etools/applications/psea/models.py
src/etools/applications/psea/notifications/assessment-assigned.py
src/etools/applications/psea/tests/test_models.py
src/etools/applications/psea/validation.py

PSEA notifications

---

src/etools/applications/action_points/signals.py
src/etools/applications/psea/__init__.py
src/etools/applications/psea/apps.py
src/etools/applications/psea/models.py
src/etools/applications/psea/tests/test_models.py
src/etools/applications/psea/tests/test_views.py

[ch15937]
Signals was not setup correctly in psea module.

PSEA action point email assigned

---

src/etools/applications/psea/models.py
src/etools/applications/psea/permission_matrix/assessment_permissions.csv
src/etools/applications/psea/permissions.py
src/etools/applications/psea/tests/test_views.py

Prevent external users being able to edit focal points

---

src/etools/applications/users/serializers_v3.py
src/etools/applications/users/tests/test_views_v3.py

Ensure country override set when adding external user to tenant

---

src/etools/applications/psea/serializers.py
src/etools/applications/psea/tests/test_views.py

Assessment date not required in initial states

---

src/etools/applications/psea/serializers.py
src/etools/applications/psea/tests/test_views.py

Handle blank value for assessment date

---

src/etools/applications/partners/permission_matrix/intervention_permissions.csv
src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_api_interventions.py

Reporting requirements can be added for contingency PDs in signed state

---

src/etools/applications/audit/management/commands/update_audit_permissions.py
src/etools/applications/audit/tests/test_views.py

Allow unicef users to add action points

---

src/etools/applications/audit/management/commands/update_audit_permissions.py

[ch13835] FAM change permissions

---

src/etools/applications/hact/models.py
src/etools/applications/partners/models.py

[ch16534] hact dash remove hact active filter

---

src/etools/__init__.py

Revert "7.6"

---

src/etools/applications/action_points/migrations/0011_actionpoint_reference_number.py

`get_reference_number` method is not available

Correct action point migration

---

src/etools/applications/psea/models.py
src/etools/applications/psea/notifications/assessment-final.py
src/etools/applications/psea/serializers.py
src/etools/applications/psea/tests/test_models.py
src/etools/applications/psea/validation.py

Fix final PSEA email

---

src/etools/applications/partners/serializers/agreements_v2.py
src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_api_agreements.py
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/tests/test_views.py

[ch13116]
Initially had the validation on the `AgreementAmendment` model, needs to be on the `InterventionAmendment` model

Amendment signed date validation changes

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_api_interventions.py

Correct validation message for PD amendment signed date

---

src/etools/applications/users/views.py

[ch15594] [ch15952] FAM/PSEA redirect

---

src/etools/applications/management/handlers/sections.py
src/etools/applications/management/tests/handlers/test_sections.py

[ch16913] section management for FAM engagements

---

src/etools/applications/core/data/attachments_file_types.json

Added group by option for psea_answer codes

Update attachment filetypes fixture

---

src/etools/applications/psea/models.py
src/etools/applications/psea/validation.py

[ch17313]
new Assessment, when the user selects the Partner Organization, we
should look up any "High" rating and "Finalized" assessments completed
for this partner in the last 365 days. If there is an assessment, then
copy all answered fields (Ratings for Questions, and Attachments) in
previous assessment to the new record.

Copy answers for assessment

---

src/etools/applications/audit/serializers/engagement.py
src/etools/applications/audit/tests/test_views.py

Add name to offices/sections datasets in engagements

---

src/etools/applications/partners/models.py

[ch14496] fix assurance calculation

---

src/etools/applications/management/handlers/sections.py
src/etools/applications/management/tests/handlers/test_sections.py

[ch16455] change name for inactive sections

---

.gitignore
src/etools/applications/users/views.py

[ch15952] fix module redirect

---

src/etools/applications/core/data/attachments_file_types.json
src/etools/applications/core/data/psea_indicators.json
src/etools/applications/psea/serializers.py

Fix PSEA text

---

src/etools/applications/core/data/attachments_file_types.json
src/etools/applications/core/data/psea_indicators.json
src/etools/applications/psea/serializers.py

[hotfix] ix PSEA text

---

src/etools/applications/field_monitoring/planning/serializers.py
src/etools/applications/field_monitoring/planning/views.py

[Field monitoring] show inactive contacts differently

---

src/etools/config/settings/base.py

Use cache backend instead of DB backend

Change celery settings.

---

src/etools/applications/field_monitoring/data_collection/offline/blueprint.py
src/etools/applications/field_monitoring/data_collection/tests/test_offline.py
src/etools/applications/field_monitoring/planning/apps.py
src/etools/applications/field_monitoring/planning/signals.py
src/etools/applications/field_monitoring/planning/tests/test_models.py
src/etools/applications/field_monitoring/planning/tests/test_views.py

[Field Monitoring] Create base question template for new question automatically

---

src/etools/applications/field_monitoring/planning/activity_validation/validations/state.py

[ch17905]
updated text for related activity entries; fixed typo in activity required questions error text

[Field Monitoring] Update error texts

---

src/etools/applications/field_monitoring/fm_settings/serializers.py
src/etools/applications/field_monitoring/fm_settings/tests/test_views.py
src/etools/applications/field_monitoring/fm_settings/views.py

[Field Monitoring] make file types required where they are

---

src/etools/applications/field_monitoring/data_collection/offline/blueprint.py
src/etools/applications/field_monitoring/data_collection/offline/helpers.py
src/etools/applications/field_monitoring/data_collection/tests/test_offline.py
src/etools/applications/field_monitoring/data_collection/views.py
src/etools/applications/offline/fields/combined.py
src/etools/applications/offline/fields/files.py
src/etools/applications/offline/tasks.py

fixed empty checklist created if something went wrong during form validation;
fixed 500 if findings are missing for provided ids;
fixed user searching: now it's allowed to pass email through body;
added user mapping to checklist attachments during offline form submit;
updated target questions to be not required as we can attach only narrative/attachments without filling in questions

[Field Monitoring] Offline collect endpoint improvements & fixes

---

src/etools/applications/audit/views.py

Search offices on engagements

---

src/etools/applications/partners/models.py
src/etools/applications/partners/permission_matrix/agreement_permissions.csv
src/etools/applications/partners/permissions.py
src/etools/applications/partners/serializers/agreements_v2.py
src/etools/applications/partners/tests/test_api_agreements.py
src/etools/applications/partners/tests/test_validation_agreements.py
src/etools/applications/partners/validation/agreements.py

Add termination letter requirement for PCA agreements marked terminated

---

src/etools/applications/field_monitoring/data_collection/tests/test_offline.py
src/etools/applications/field_monitoring/data_collection/views.py
src/etools/applications/field_monitoring/planning/models.py

[Field Monitoring] Use permissions matrix for offline data collection

---

src/etools/applications/field_monitoring/data_collection/serializers.py
src/etools/applications/field_monitoring/data_collection/tests/test_views.py

[Field Monitoring] Add checklist id to activity overall findings

---

src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
src/etools/applications/field_monitoring/planning/tests/test_models.py
src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/field_monitoring/planning/views.py

[Field Monitoring] set location to be required in draft

---

src/etools/applications/field_monitoring/fm_settings/views.py
src/etools/applications/field_monitoring/planning/serializers.py
src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/field_monitoring/planning/views.py

[ch18066]
depends from https://github.com/unicef/etools/pull/2663

[Field Monitoring] Standardize sorting order for all dropdown lists

---

src/etools/applications/field_monitoring/data_collection/tests/test_views.py

actually, there was a possibility to remove checklists. so, just added more tests
[ch17913]

[Field Monitoring] Add tests to cover activity checklists removing

---

src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/tests/test_validation_interventions.py
src/etools/applications/partners/validation/interventions.py

Pmp prp mandatory integration

---

src/etools/applications/partners/synchronizers.py

[ch19532]
Mapping does not actually handle the setting of values!

Actually save psea data in vision sync

---

.gitignore
src/etools/applications/partners/tests/test_validation_interventions.py
src/etools/applications/partners/validation/interventions.py

[ch17619]
Ensure that outstanding DCT is zero

Update PD transition to close validation on outstanding DCT

---

src/etools/applications/partners/tests/test_api_pmp.py
src/etools/applications/partners/tests/test_views.py
src/etools/applications/partners/views/partner_organization_v2.py
src/etools/applications/partners/views/v2.py

Psea assessment filters

---

src/etools/applications/partners/synchronizers.py

Correct short name sync key

---

src/etools/applications/partners/views/v2.py

Exclude empty sea risk rating name values in static dropdown

---

src/etools/applications/partners/admin.py

Add partner psea assessment fields to admin

---

src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/tests/test_validation_interventions.py
src/etools/applications/partners/validation/interventions.py

Reverse PMP PRP mandatory integration

---

src/etools/applications/attachments/permissions.py
src/etools/applications/attachments/tests/test_views.py
src/etools/applications/core/tests/cases.py
src/etools/config/settings/base.py

Require schema to be set for attachment endpoints

---

src/etools/applications/hact/tests/test_views.py
src/etools/applications/hact/views.py

Update hact graph api endpoint requires authenticated user

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIIntervention/_api_v2_interventions_/get/None.response.json
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/views/interventions_v2.py

Add contingency_pd to payload and allowed in filtering

---

src/etools/applications/audit/tests/test_views.py
src/etools/applications/audit/views.py

Add vendor_number and short_name as search options on engagement endpoint

---

src/etools/applications/action_points/tasks.py

Fix link in action points overdue email message

---

src/etools/applications/field_monitoring/data_collection/tests/test_offline.py
src/etools/applications/field_monitoring/planning/activity_validation/validator.py
src/etools/applications/field_monitoring/planning/models.py
src/etools/applications/field_monitoring/planning/notifications/activity-assign.py
src/etools/applications/field_monitoring/planning/notifications/activity-reject.py
src/etools/applications/field_monitoring/planning/notifications/activity-rejected-responible.py
src/etools/applications/field_monitoring/planning/notifications/activity-staff-assign.py
src/etools/applications/field_monitoring/planning/notifications/activity-staff-reject.py
src/etools/applications/field_monitoring/planning/notifications/activity-staff-submit.py
src/etools/applications/field_monitoring/planning/notifications/activity-submit.py
src/etools/applications/field_monitoring/planning/tests/test_views.py

[ch21567]
[ch21571]
[ch21573]
[ch21569]
[ch21572]
[ch21568]

Send relevant email on FM Activity actions

---

src/etools/applications/partners/migrations/0026_save_interventions.py
src/etools/applications/partners/prp_api.py
src/etools/applications/partners/tasks.py
src/etools/applications/partners/tests/test_prp_sync.py
src/etools/applications/partners/utils.py

[ePD] Sync PRP users to eTools

---

Dockerfile
Dockerfile-base

Stick with alpine v3.11 for packages

Fix base docker image

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py
src/etools/applications/partners/views/v3.py

[ch21912]
added test to check intervention create permissions. configured permissions to handle anonymous user properly

[ePD] Create pd endpoint cleanup

---

src/etools/applications/partners/tests/test_v3_interventions.py

ePD update detail tests

---

src/etools/applications/partners/tests/test_api_pmp.py
src/etools/applications/partners/views/v2.py
src/etools/applications/psea/admin.py

[ePD] Add ratings to static dropdowns

---

src/etools/applications/comments/serializers.py
src/etools/applications/comments/tests/test_views.py

[ePD] Add time to comments

---

src/etools/applications/partners/serializers/v3.py
src/etools/applications/partners/tests/test_v3_intervention_lower_results.py

[ePD] Strange behavior when saving Unassociated PD Output

---

src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py

[ePD] Add possibility to remove intervention supply items

---

src/etools/applications/hact/tests/test_models.py
src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_models.py
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPICartoDB/_locations_cartodbtables_/get/None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/_api_locations-light_/get/None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/_api_locations-types_/get/None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/_api_locations_/get/None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/_api_locations_101_/get/None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/_api_locations_pcode_abc_/get/None.response.json
src/etools/libraries/locations/tests/_api_checker/etools.libraries.locations.tests.test_api/TestAPILocations/_locations_autocomplete_/get/None.response.json

change minimum pv requirements calculation

---

src/etools/applications/partners/tests/test_api_pmp.py
src/etools/applications/partners/views/v2.py

[ePD] Add cash transfer modalities choices to static dropdowns

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/tests/test_v3_interventions.py

[ePD] 500 error for interventions list if result link having no cp output exists

---

src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
src/etools/applications/field_monitoring/planning/filters.py
src/etools/applications/field_monitoring/planning/tests/factories.py
src/etools/applications/field_monitoring/planning/tests/test_views.py

[FM] Field office field on FMA

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py

[ch22493]
Allow searching on cfei_number in intervention list api endpoint

Add cfei_number to intervention list results

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_interventions.py

[ePD] Add partner and unicef totals to ManagementBudget serializer

---

src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/urls_v3.py
src/etools/applications/partners/views/interventions_v3.py

[ch22641]
Resutls includes complete PD data

[ePD] Add applied indicator endpoint to pmp v3

---

src/etools/applications/partners/tests/test_v3_intervention_activity.py
src/etools/applications/reports/serializers/v2.py

[ePD] Epd use ids for intervention time frames

---

src/etools/applications/partners/tests/test_v3_agreements.py
src/etools/applications/partners/views/agreements_v3.py

[ePD] Add serialiser for partner in agreement SERIALIZER_OPTIONS

---

src/etools/applications/comments/export/renderers.py
src/etools/applications/comments/export/serializers.py
src/etools/applications/comments/tests/test_views.py
src/etools/applications/comments/views.py
src/etools/applications/users/tests/factories.py

[ePD] Export comments csv

---

.circleci/config.yml
utils/trigger_redeploy.py

I think this is all that needs to be done.
Did not see any config options in CircleCI that applied to this

[ePD] Add epd branch to list of DEPLOY_BRANCHES in circleci

---

src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py

[ePD] Update Intervention update endpoint to update planned budget data

---

src/etools/applications/core/tests/factories.py
src/etools/applications/partners/notifications/intervention-unicef_terminated.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3_actions.py

[ePD] Fix/add notifications

---

src/etools/applications/partners/serializers/partner_organization_v3.py
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/tests/test_v3_partner_organizations.py
src/etools/applications/partners/tests/test_v3_pmp_dropdowns.py
src/etools/applications/partners/urls_v3.py
src/etools/applications/partners/views/interventions_v3.py
src/etools/applications/partners/views/partner_organization_v3.py
src/etools/applications/partners/views/v3.py
src/etools/applications/reports/tests/test_v3_views.py
src/etools/applications/reports/tests/test_views.py
src/etools/applications/reports/urls_v3.py
src/etools/applications/reports/views/v3.py
src/etools/config/urls.py

[ePD] Add partner list v3 endpoint

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_serializers_intervention.py

[ePD] Handle cancelled to status list in serializer

---

src/etools/applications/partners/views/v3.py

Correct cso_type query in v3 dropdown endpoint

---

src/etools/applications/partners/tests/test_v3_intervention_activity.py
src/etools/applications/partners/views/interventions_v3.py

Do not cache intervention data in PD Activity view

---

src/etools/applications/partners/models.py
src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/serializers/v3.py
src/etools/applications/partners/tests/test_models.py
src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/reports/models.py
src/etools/applications/reports/tests/test_models.py

[ePD] Add totals to LowerResult and ResultLink models/serializers

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_serializers_intervention.py

[ePD] Add closed status to status lists, where applicable

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_serializers_intervention.py

[ePD] Correct terminate action in available actions

---

src/etools/applications/partners/tests/test_v3_partner_organizations.py
src/etools/applications/partners/views/partner_organization_v3.py

[ePD] Fix v3 partners endpoint for UNICEF users

---

src/etools/applications/partners/views/interventions_v3.py

[ch23009]
Was not picking up updates to the intervention

[ePD] Remove simple caching functionality on intervention data

---

src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_models.py

[ePD] Set default currency value for InterventionBudget

---

src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_models.py

[ePD] Automatically set PD contrib to 7% for INGOs

---

src/etools/applications/partners/tests/test_v3_agreements.py
src/etools/applications/partners/views/agreements_v3.py

[ePD] Correct Agreement patch request issue

---

src/etools/applications/partners/tests/test_v3_agreements.py
src/etools/applications/partners/views/agreements_v3.py
src/etools/libraries/djangolib/views.py

[ch22809]
Now agreement list returns empty list if partner not related

Update agreement v3 endpoints to make use of ExternalModuleFilterMixin

---

src/etools/applications/comments/tests/factories.py
src/etools/applications/reports/tests/test_v3_views.py
src/etools/applications/reports/views/v3.py
src/etools/libraries/djangolib/views.py

[ch22810]
This PR is based off `epd-psm` and currently merging back there, till we merge with `epd` branch

[ePD] Update section/office v3 endpoints to return empty lists where applicable

---

src/etools/applications/partners/templates/pd/detail.html
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/urls_v3.py
src/etools/applications/partners/views/interventions_v3.py

[ch22653]
Just framework in place, still need format/styling for the page
Endpoint is `/api/pmp/v3/interventions/<int:pd-pk>/pdf/`

Add pd pdf export endpoint

---

src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py

[ePD] fix 500 error when editing/deleting Supply item while logged in as partner user

---

src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_validation_interventions.py
src/etools/applications/partners/validation/interventions.py

[ePD] Final partnership review: invalid attachments should be ignored

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_interventions.py

[ePD] Show readable errors for supply items csv

---

src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
src/etools/applications/partners/views/interventions_v3.py

[ePD] Fix applied indicators permissions

---

src/etools/applications/field_monitoring/data_collection/offline/helpers.py
src/etools/applications/field_monitoring/data_collection/tests/test_offline.py

Add information_source validation on checklist blueprint endpoint

---

src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/field_monitoring/planning/views.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/users/serializers_v3.py

Add phone field to v3 MinimalUserSerializer

---

src/etools/applications/partners/tasks.py

sync partner in admin

---

src/etools/applications/field_monitoring/planning/filters.py
src/etools/applications/field_monitoring/planning/tests/test_views.py

Add sections filter to MonitoringActivity

---

src/etools/applications/field_monitoring/planning/serializers.py
src/etools/applications/field_monitoring/planning/tests/test_views.py

[ch20451]
Added `sections` to payload on FM planning activities endpoint

Add sections to FM activities serializer

---

src/etools/applications/partners/exports_v2.py
src/etools/applications/partners/serializers/exports/interventions.py
src/etools/applications/partners/tests/factories.py
src/etools/applications/partners/tests/test_export_intervention.py
src/etools/applications/partners/tests/test_exports.py

[ePD] csv fix empty intervention country programmes

---

src/etools/applications/partners/tests/test_v3_agreements.py
src/etools/applications/partners/views/agreements_v3.py

Update Agreement partner staff member reference

---

src/etools/applications/partners/permission_matrix/intervention_permissions.csv
src/etools/applications/partners/tests/test_epd_management/test_signed_documents.py

Update permission on submission_date field

---

src/etools/applications/partners/tests/test_api_interventions.py

Add complete contingency pd filter tests

---

src/etools/applications/management/handlers/sections.py

Correct filtering on fm activities in close handler

---

src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py

[ePD] Fix partner user permissions for intervention pdf export

---

src/etools/applications/hact/tests/test_models.py
src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_models.py

remove covid constraint

---

src/etools/applications/psea/serializers.py

[ch17205] amend psea export: added overall risk rating

---

src/etools/applications/field_monitoring/analyze/serializers.py
src/etools/applications/field_monitoring/analyze/tests/test_views.py

[ch24679] PartnerPlannedVisits for 2022

---

src/etools/applications/reports/synchronizers.py

[ch25163] amend ram sync

---

src/etools/applications/action_points/filters.py

[ch25159] action point fm filter

---

src/etools/applications/field_monitoring/analyze/serializers.py
src/etools/applications/field_monitoring/analyze/tests/test_views.py

[ch23935] overall planned visits

---

src/etools/applications/reports/migrations/0023_auto_20191014_1546.py

[ch25197] fix add_country command

---

src/etools/applications/psea/views.py

[ch15114] psea assessment: added sea_risk_rating filter

---

src/etools/libraries/azure_graph_api/utils.py

https://excubo.unicef.io/sentry/etools-staging/issues/1256/?query=is%3Aunresolved

sentry staging 1256

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_v3_interventions.py

Add field length validation on some PD fields

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_serializers_intervention.py

Correct default_ordering list for available actions

---

src/etools/applications/partners/templates/pca/arabic_pdf.html
src/etools/applications/partners/templates/pca/english_pdf.html
src/etools/applications/partners/templates/pca/french_pdf.html
src/etools/applications/partners/templates/pca/ifrc_english_pdf.html
src/etools/applications/partners/templates/pca/ifrc_french_pdf.html
src/etools/applications/partners/templates/pca/portuguese_pdf.html
src/etools/applications/partners/templates/pca/russian_pdf.html
src/etools/applications/partners/templates/pca/spanish_pdf.html
src/etools/applications/partners/views/v1.py

[ch25080] somalia bank tax #5

---

src/etools/applications/psea/serializers.py

[ch17205] psea sea export name

---

src/etools/applications/partners/exports_v2.py
src/etools/applications/partners/serializers/exports/partner_organization.py
src/etools/applications/partners/tests/test_export_partner.py
src/etools/applications/partners/tests/test_exports.py

[ch18003] tweak partner export serializer

---

src/etools/applications/field_monitoring/fm_settings/models.py

[ch25592] fm fix site creation

---

src/etools/applications/audit/views.py

[ch25292] fam staff member restore

---

src/etools/applications/psea/admin.py
src/etools/applications/psea/models.py
src/etools/applications/psea/notifications/assessment-action_point_assigned.py
src/etools/applications/psea/tests/test_models.py

[ch25833] PSEA fix assign notifications

---

src/etools/applications/psea/templates/psea_pdf.html

[ch21780] psea-export-layout

---

src/etools/applications/psea/serializers.py

[ch21780] psea amend export

---

src/etools/applications/psea/notifications/assessment-action_point_assigned.py

[ch25833] fix psea ap notification

---

src/etools/applications/partners/amendment_utils.py
src/etools/applications/partners/models.py
src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_amendments.py
src/etools/applications/partners/tests/test_api_amendments.py
src/etools/applications/partners/validation/interventions.py
src/etools/applications/partners/views/interventions_v3_actions.py
src/etools/applications/reports/models.py

[ePD] Intervention amendments: no-review type, custom names in difference, save difference on review

---

src/etools/applications/psea/notifications/assessment-action_point_assigned.py

[ch25833] fix psea notification

---

src/etools/applications/field_monitoring/data_collection/offline/synchronizer.py
src/etools/applications/field_monitoring/data_collection/tests/test_offline.py

[FM] don't fail in case of unavailable offline backend

---

src/etools/applications/partners/serializers/interventions_v2.py

[ch26185] fix inactive indicator display

---

src/etools/applications/action_points/admin.py
src/etools/applications/field_monitoring/planning/notifications/fm-action_point_assigned.py
src/etools/applications/field_monitoring/planning/signals.py

[ch26210] FM action-points

---

src/etools/applications/action_points/serializers.py
src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_views.py

[ch25641] action point intervetion list serializer

---

src/etools/applications/partners/permission_matrix/intervention_permissions.csv
src/etools/applications/partners/permissions.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/validation/interventions.py

[ePD] Validations in Review should be moved when UNICEF accepts

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_serializers_intervention.py

[ePD] Cancel button should only be visible to focal points and business owner

---

src/etools/applications/partners/tests/test_v3_agreements.py
src/etools/applications/partners/views/agreements_v3.py

[ePD] Backend error on Exporting list of agreements

---

src/etools/applications/action_points/admin.py
src/etools/applications/field_monitoring/planning/admin.py
src/etools/applications/psea/admin.py
src/etools/applications/t2f/admin.py
src/etools/applications/tpm/admin.py
src/etools/applications/tpm/migrations/0006_auto_20180522_0736.py
src/etools/applications/tpm/models.py

[ch26385] action point admin

---

src/etools/applications/audit/tests/test_views.py
src/etools/applications/audit/views.py

Story details: https://app.clubhouse.io/unicefetools/story/26407

[FAM] On Engagement List  an API is taking long to load

---

src/etools/applications/partners/models.py
src/etools/applications/partners/permission_matrix/intervention_permissions.csv
src/etools/applications/partners/permissions.py
src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/factories.py
src/etools/applications/partners/tests/test_amendments.py
src/etools/applications/partners/tests/test_epd_management/test_risks.py
src/etools/applications/partners/tests/test_v3_serializers_intervention.py
src/etools/applications/partners/validation/interventions.py
src/etools/applications/partners/views/interventions_v3_actions.py

Epd tweaks

---

src/etools/applications/partners/permission_matrix/intervention_permissions.csv
src/etools/applications/partners/permissions.py
src/etools/applications/partners/tests/test_api_amendments.py
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/tests/test_api_prp.py
src/etools/applications/partners/tests/test_epd_management/base.py
src/etools/applications/partners/tests/test_models.py
src/etools/applications/partners/tests/test_utils.py
src/etools/applications/partners/tests/test_v3_intervention_activity.py
src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/tests/test_views.py
src/etools/applications/reports/tests/test_v3_views.py

Make only focal points able to edit

---

src/etools/applications/users/admin.py

[ch26903] hide fund commitment button from admin

---

src/etools/applications/partners/views/interventions_v2.py

[ch20495] added grant filter for intervention export

---

src/etools/applications/audit/purchase_order/templates/admin/purchase_order/change_form.html
src/etools/applications/partners/templates/admin/partners/partnerorganization/change_form.html

Story details: https://app.shortcut.com/unicefetools/story/27250

[ch26933] In admin Auditor Staff Member and Purchase Order pages throw a 500 error

---

src/etools/applications/audit/filters.py

[ch27547]Draft Report Issued to IP filter

---

src/etools/applications/partners/templates/pca/russian_pdf.html

https://excubo.unicef.io/sentry/etools-prod/issues/5548/?query=is%3Aunresolved

sentry-5548: fix russian template

---

src/etools/applications/psea/tests/test_models.py
src/etools/applications/reports/tests/test_synchronizers.py

there were some hardcoded year values in tests

[ePD] fix tests broken by year shift

---

src/etools/applications/field_monitoring/data_collection/offline/blueprint.py
src/etools/applications/field_monitoring/data_collection/tests/test_offline.py
src/etools/applications/offline/fields/base.py
src/etools/applications/offline/tests/test_contact_book_example.py
src/etools/applications/offline/tests/test_validations.py
src/etools/applications/offline/validations/text.py

Story details: https://app.shortcut.com/unicefetools/story/27364

[OLC] Source of Information field blocking submission of  forms and inconsistencies with FM side

---

src/etools/applications/partners/admin.py
src/etools/applications/reports/models.py

fix for sentry issue #ETOOLS-PROD-EH when deleting an agreement
https://excubo.unicef.io/sentry/etools-prod/issues/5922/

[ch27970] sentry-5922: Admin: agreement __str__ issue

---

src/etools/applications/audit/migrations/0022_engagement_reference_number.py

[ch28019] Error on running migrations on etools-test

---

src/etools/applications/partners/tasks.py
src/etools/applications/partners/tests/test_api_partners.py
src/etools/applications/partners/urls_v2.py
src/etools/applications/partners/views/partner_organization_v2.py

[ch24369] add -> sync partner API

---

src/etools/applications/reports/serializers/v2.py
src/etools/applications/reports/tests/test_views.py

[ePD] settings disaggregation validation

---

src/etools/applications/field_monitoring/data_collection/tests/test_views.py
src/etools/applications/field_monitoring/planning/models.py

Story details: https://app.shortcut.com/unicefetools/story/28262

[FM] Porting over of findings from data collection to summary analysis

---

src/etools/applications/travel/models.py
src/etools/applications/travel/serializers.py
src/etools/applications/travel/tests/test_views.py

[ch28519] Trips: Add cancel comment

---

src/etools/applications/field_monitoring/planning/admin.py
src/etools/config/settings/base.py

[ch28560] Admin Monitoring Activity slow loading fix

---

src/etools/applications/field_monitoring/fm_settings/views.py

[ch28554] archived location path excludes archived

---

src/etools/applications/travel/models.py
src/etools/applications/travel/serializers.py
src/etools/applications/travel/tests/test_serializers.py
src/etools/applications/travel/tests/test_views.py
src/etools/applications/travel/views.py

[ch28549] Trips: Remove REVIEW status logic (commented out)

---

src/etools/applications/audit/conditions.py
src/etools/applications/audit/management/commands/update_audit_permissions.py
src/etools/applications/audit/tests/test_views.py
src/etools/applications/audit/views.py

[ch28458] FAM: users_notified not editable for non-staff auditor

---

src/etools/applications/field_monitoring/fm_settings/tests/test_views.py
src/etools/applications/field_monitoring/fm_settings/views.py

[sentry-6294][ch28731] FM: Multiple Locations Level 0

---

src/etools/applications/firms/tests/factories.py

[ch28688] Fix random test failures related to user emails

---

src/etools/applications/travel/tests/test_views.py
src/etools/applications/travel/views.py

[ch28881] Trips: delete endpoint for draft trips only

---

src/etools/applications/travel/models.py
src/etools/applications/travel/serializers.py
src/etools/applications/travel/tests/test_serializers.py
src/etools/applications/travel/tests/test_views.py
src/etools/applications/travel/views.py

[ch28905]Trips: Add new action to skip supervisor approval

---

src/etools/applications/audit/tests/test_transitions.py
src/etools/applications/audit/utils.py
src/etools/applications/core/data/attachments_file_types.json
src/etools/applications/partners/utils.py

[ch28499] fix attachments filetype group

---

src/etools/applications/audit/models.py

[ch28830] Admin integrity err on total_value and exchange_rate blank

---

src/etools/applications/partners/tests/test_export_partner.py
src/etools/applications/partners/tests/test_exports.py
src/etools/applications/partners/views/partner_organization_v2.py

[ch28836] export csv

---

src/etools/applications/partners/admin.py

[ch29091] ePD: admin partner staff members search error

---

src/etools/applications/partners/admin.py

[ch29624] ePD: add activation_protocol to InterventionAdmin

---

src/etools/applications/audit/serializers/engagement.py
src/etools/applications/audit/templates/audit/audit_pdf.html

[ch28981] FAM: adjusted inconsistencies on audit pdf export

---

src/etools/applications/partners/serializers/partner_organization_v2.py
src/etools/applications/partners/tests/test_api_partners.py

[ch29621] ePD: creating partner staff member has user with wrong last name

---

src/etools/applications/partners/models.py
src/etools/applications/partners/notifications/intervention-prc_review_sent_back.py
src/etools/applications/partners/views/interventions_v3_actions.py

[ch29622] ePD:  PRC secretary send back and sent for review malformed email url

---

src/etools/applications/reports/migrations/0039_auto_20220222_1135.py
src/etools/applications/reports/migrations/0043_auto_20220510_0717.py

drop codes for lower results before updating values to calculated ones

[ePD] Fix lower results auto numbering IntergityError in migrations

---

src/etools/applications/t2f/admin.py

[ch29669] t2f: T2FActionPointAdmin status is readonly so that direct modification is not allowed

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/serializers/interventions_v3.py

[ch29908] Character count for Risks
[ch29905] Character count for Document Details/ Capacity Development

[ch29908][ch29905] Character count

---

src/etools/applications/partners/models.py
src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_models.py
src/etools/applications/partners/tests/test_v3_interventions.py

[ch29943] ePD: added total_supply field for unicef + partner supplies total

---

src/etools/applications/partners/serializers/v3.py
src/etools/applications/partners/tests/test_v3_intervention_lower_results.py

[ch29797] ePD Editor: fix for activity item index not updated on cp assign

---

src/etools/applications/users/models.py
src/etools/templates/admin/base_site.html

[ch29134] Admin header: add href to current user

---

src/etools/applications/partners/models.py
src/etools/applications/partners/views/v3.py

[ch30047] ePD-Updated supply item moves away in the list: order supply list by '-id'

---

src/etools/applications/partners/exports_v2.py

[ch30564] ePD: Excel Export fails when CP Output is not yet set

---

src/etools/applications/partners/tests/test_v3_intervention_activity.py
src/etools/applications/reports/serializers/v2.py

[ch30506] ePD: fix for deleting all activity items

---

src/etools/applications/action_points/admin.py

[ch30355] sentry-9811: actionpoints direct status modification not allowed

---

src/etools/applications/action_points/admin.py

[ch29575] Sentry-8685: use admin view_on_site url 

---

src/etools/applications/field_monitoring/planning/activity_validation/validator.py
src/etools/applications/field_monitoring/planning/tests/test_models.py

[ch19711] comment validation

---

Pipfile
Pipfile.lock

Bump unicef-attachments version to 0.11

---

src/etools/applications/action_points/views.py

[ch30812] fix AP search

---

src/etools/applications/t2f/admin.py

[ch30170] T2f: travel activity admin search by reference number

---

src/etools/applications/field_monitoring/planning/models.py
src/etools/applications/field_monitoring/planning/notifications/activity-reject-pme.py
src/etools/applications/field_monitoring/planning/tests/test_views.py

[ch30791] FM Rejection Notification to lead visit

---

src/etools/applications/partners/models.py
src/etools/applications/partners/serializers/v3.py
src/etools/applications/partners/tests/test_models.py
src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
src/etools/applications/reports/models.py

disable pd output deactivation logic + add created field to check whether instance was created during amendment session or not

[ePD] Can't delete an activity when in Amendment #2

---

src/etools/applications/field_monitoring/fm_settings/models.py

[ch31608][FM]: Import sites: fix for creating new location with given parent id

---

src/etools/applications/partners/tests/test_v3_intervention_results_structure.py
src/etools/applications/reports/serializers/v2.py

[ch31601] ePD: Added "created" field to Activities list on results-struct endpoint

---

src/etools/applications/partners/tests/test_v3_intervention_results_structure.py

tests broken on ePD from adding created field

fix tests on results-structure 'created' field

---

src/etools/config/settings/local.py

work with jwt RS256 locally
enable testing locally on multiple threads, adjust the threads wih an env var

update local settings

---

src/etools/libraries/cache_keys/redis.py

Story details: https://app.shortcut.com/unicefetools/story/32055

[FM] Sites are not displayed after save

---

src/etools/applications/field_monitoring/fm_settings/views.py
src/etools/applications/locations/views.py

Story details: https://app.shortcut.com/unicefetools/story/32092

[FM] Sites are not updated when changing the country

---

src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/partners/tests/test_tasks.py
src/etools/applications/reports/models.py
src/etools/applications/reports/serializers/v2.py
src/etools/applications/reports/tests/factories.py

Story details: https://app.shortcut.com/unicefetools/story/31028

[FM] please limit the CP output selection in FMM dropdown

---

src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
src/etools/applications/field_monitoring/planning/tests/test_views.py

Story details: https://app.shortcut.com/unicefetools/story/28917

[FM] Move assignment of Action Points to "Report Review" to allow Visit Lead to assign action points (not just PME users)

---

src/etools/applications/partners/permission_matrix/intervention_permissions.csv

restrict partner user attachments flags access
#3415

[ePD] Remove validation on the 3 newly added checkboxes #2

---

src/etools/applications/comments/tests/test_views.py
src/etools/applications/comments/views.py

When exporting comments file, the deleted comments should not be visible

---

src/etools/applications/partners/models.py

on PDF export of PD, cash transfer modality shows up unkown

---

src/etools/applications/partners/admin.py
src/etools/applications/partners/locale/ar/LC_MESSAGES/django.po
src/etools/applications/partners/locale/es/LC_MESSAGES/django.po
src/etools/applications/partners/locale/fr/LC_MESSAGES/django.po
src/etools/applications/partners/locale/pt/LC_MESSAGES/django.po
src/etools/applications/partners/locale/ru/LC_MESSAGES/django.po

[ch32811] open "UNICEF Editing" field for edit by the "Country Office Administrator

---

src/etools/applications/ecn/serializers.py

Story details: https://app.shortcut.com/unicefetools/story/32388

[ch32388] Add new fields to eCN

---

src/etools/applications/partners/permission_matrix/intervention_permissions.csv
src/etools/applications/partners/tests/test_epd_management/test_programmatic_visits.py

Changed edit permissions to Unicef focal point & PME on planned_visits

---

src/etools/applications/partners/templates/pca/english_pdf.html

[ch33084] Update PCA Template

---

src/etools/applications/partners/serializers/exports/vision/export_mixin.py
src/etools/applications/partners/serializers/interventions_v2.py

Sentry ETOOLS-DEMO-24 - fix on send_pd_to_vision error

---

src/etools/applications/partners/notifications/intervention-amendment-added.py
src/etools/applications/partners/notifications/intervention-draft.py
src/etools/applications/partners/notifications/intervention-new_pca_required.py
src/etools/applications/partners/notifications/intervention-partner_accepted.py
src/etools/applications/partners/notifications/intervention-partner_unlocked.py
src/etools/applications/partners/notifications/intervention-past-start.py
src/etools/applications/partners/notifications/intervention-pca_missing.py
src/etools/applications/partners/notifications/intervention-prc-review-notification.py
src/etools/applications/partners/notifications/intervention-prc_review_sent_back.py
src/etools/applications/partners/notifications/intervention-send_to_partner.py
src/etools/applications/partners/notifications/intervention-send_to_unicef.py
src/etools/applications/partners/notifications/intervention-unicef-accepted-behalf-of-partner.py
src/etools/applications/partners/notifications/intervention-unicef_cancelled.py
src/etools/applications/partners/notifications/intervention-unicef_rejected_review.py
src/etools/applications/partners/notifications/intervention-unicef_signature.py
src/etools/applications/partners/notifications/intervention-unicef_suspended.py
src/etools/applications/partners/notifications/intervention-unicef_terminated.py
src/etools/applications/partners/notifications/intervention-unicef_unsuspended.py
src/etools/applications/partners/notifications/partnership-ended-frs-outstanding.py
src/etools/applications/partners/notifications/partnership-ending.py
src/etools/applications/partners/notifications/partnership-signed-frs.py
src/etools/applications/partners/utils.py

[ch33237] Partners: email notifications update

---

src/etools/applications/partners/templates/pca/english_pdf.html

[ch33317] Fix bank details value not showing inside table

[ch33317] Fix bank details value not showing inside table

---

src/etools/applications/partners/tests/test_api_amendments.py
src/etools/applications/partners/views/interventions_v2.py

[ch33298] Email not sent when an intervention amendment is added

---

src/etools/applications/partners/exports_v2.py

[ch33553] Excel export error

---

src/etools/applications/core/templatetags/etools.py
src/etools/applications/partners/templates/pca/english_pdf.html

[ch33836] Upda PCA Template

---

src/etools/applications/partners/filters.py
src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_export_partner.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/tests/test_v3_partner_organizations.py
src/etools/applications/partners/tests/test_views.py
src/etools/applications/partners/urls_v2.py
src/etools/applications/partners/views/partner_organization_v2.py
src/etools/applications/partners/views/partner_organization_v3.py
src/etools/applications/partners/views/v3.py
src/etools/applications/tpm/views.py
src/etools/applications/users/admin.py
src/etools/applications/users/filters.py
src/etools/applications/users/tests/test_views_v3.py
src/etools/applications/users/views_v3.py

Fixes for has_active_realm to be in current context

---

src/etools/applications/audit/serializers/engagement.py
src/etools/applications/audit/tests/test_views.py

[ch33860] AMP: audit staff-members label missing

---

src/etools/applications/field_monitoring/planning/filters.py
src/etools/applications/field_monitoring/planning/serializers.py
src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/field_monitoring/planning/views.py
src/etools/applications/partners/tasks.py

[ch33870] 
sentry https://excubo.unicef.io/sentry/etools-dev/issues/22328/

[ch33870] AMP: added tpm staff member not displayed

---

src/etools/applications/core/jwt_api.py
src/etools/applications/ecn/api.py
src/etools/applications/partners/prp_api.py
src/etools/applications/partners/signals.py
src/etools/applications/partners/tasks.py
src/etools/applications/partners/tests/test_prp_sync.py
src/etools/applications/partners/tests/test_tasks.py
src/etools/applications/partners/utils.py
src/etools/applications/users/admin.py
src/etools/applications/users/signals.py
src/etools/applications/users/tasks.py
src/etools/applications/users/views_v3.py
src/etools/config/settings/base.py

1.using JWT api authentication for PRP
2.moved tasks
3.commented deprecated code for cleanup

Sync realms from etools

---

src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv

Story details: https://app.shortcut.com/unicefetools/story/33842

[FM] Action Points to be hidden for the TPM user

---

src/etools/applications/audit/serializers/risks.py
src/etools/applications/core/data/audit_risks_blueprints.json

Story details: https://app.shortcut.com/unicefetools/story/33736

[FAM] Change Micro Assessment Questionnaire #2

---

src/etools/applications/tpm/tests/test_views.py
src/etools/applications/tpm/views.py

[ch34051] FM: A Partner user can Export the TPM Organization information even if the list is empty

---

src/etools/applications/management/tests/test_views.py
src/etools/applications/management/views/gis_v1.py

[ch34268]
Add monitoring activities & location sites to /api/management/gis/in-use/

GIS management endpoint

---

src/etools/config/settings/base.py

Story details: https://app.shortcut.com/unicefetools/story/34159

[Global] Upload files: Add a validation for accepted file formats

---

src/etools/applications/field_monitoring/planning/activity_validation/validations/basic.py
src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/tpm/tpmpartners/models.py

[ch34383] fix validation on tpm staff members that belong to the partner

---

src/etools/applications/users/views_v3.py

[ch34340]  add IsUNICEFUser permission for accept/decline endpoints

[ch34340] etools-amp: user staging request

---

src/etools/applications/audit/filters.py
src/etools/applications/audit/views.py

Story details: https://app.shortcut.com/unicefetools/story/34585

[ch34585] "Audit Staff Team Members" list takes too long to load

---

src/etools/applications/partners/mixins.py
src/etools/applications/partners/templates/pca/russian_pdf.html

[ch34711] PCA russian template not generated correctly

---

src/etools/applications/audit/templates/audit/audit_pdf.html
src/etools/applications/audit/templates/audit/engagement_pdf.html

[ch34418]"Audit Staff Team Members" information overlapping in PDF export

[ch34418]"Audit Staff Team Members" information overlapping in PDF export

---

src/etools/applications/users/serializers_v3.py
src/etools/config/settings/base.py

[ch34744] PRP realm sync data issue

---

src/etools/applications/core/data/field_monitoring_groups.json
src/etools/applications/field_monitoring/groups.py
src/etools/applications/field_monitoring/planning/activity_validation/permissions.py
src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
src/etools/applications/field_monitoring/planning/models.py
src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/field_monitoring/planning/transitions/permissions.py
src/etools/applications/field_monitoring/tests/factories.py

[ch34750] FM: add Monitoring Visit Approver role

---

src/etools/applications/partners/templates/pca/english_pdf.html
src/etools/applications/partners/templates/pca/french_pdf.html
src/etools/applications/partners/templates/pca/portuguese_pdf.html
src/etools/applications/partners/templates/pca/spanish_pdf.html

Fix texts on PCA templates

---

src/etools/__init__.py
src/etools/applications/partners/templates/pca/portuguese_pdf.html

[ch35205][Hotfix] PCA Portuguese issues

[ch35205][Hotfix] PCA Portuguese issues

---

src/etools/applications/partners/admin.py
src/etools/applications/partners/mixins.py

- remove realms country filter on 
- set staff_only to false

PD update on users in admin 

---

src/etools/applications/partners/tests/test_tasks.py
src/etools/applications/users/admin.py
src/etools/applications/users/tasks.py

[ch35256]
https://excubo.unicef.io/sentry/prp-prod/issues/41294/?query=is%3Aunresolved
+ Admin: Remove delete permission for Realm

[ch35256] Realm Sync on PRP: do not sync users without any partner roles

---

src/etools/applications/organizations/models.py
src/etools/applications/users/filters.py
src/etools/applications/users/tests/test_views_v3.py
src/etools/applications/users/views_v3.py

[ch35468] Cannot create an engagement with new PO not in the system already / Cannot add staff for auditor firms without engagements

[ch35468] FAM/AMP: allow adding staff for audit firms without engagements

---

src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
src/etools/applications/reports/serializers/v2.py

[ch35959] fix for PD in amendment inactive indicators can be edited

---

src/etools/applications/partners/admin.py

[ch35969] Admin intervention amendment timeout

---

src/etools/applications/audit/views.py

[ch35978] FAM: Add search by reference number

---

src/etools/applications/partners/exports_v2.py
src/etools/applications/partners/templates/pd/detail.html

[ch33627] [ch35987] PD exports: prefix inactive activities and indicators

---

src/etools/applications/field_monitoring/planning/filters.py
src/etools/applications/field_monitoring/planning/serializers.py
src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/field_monitoring/planning/views.py

[ch33549] FM: expired pds in dropdown

---

src/etools/applications/management/tests/test_views.py
src/etools/applications/management/views/sections.py
src/etools/applications/partners/permissions.py
src/etools/applications/reports/views/v1.py

Story details: https://app.shortcut.com/unicefetools/story/35986

[Develop] Manage app Add Sections permissions

---

src/etools/applications/field_monitoring/fm_settings/tests/test_views.py
src/etools/applications/field_monitoring/fm_settings/views.py

Story details: https://app.shortcut.com/unicefetools/story/36519

[FM] Questions table pagination is wrong, duplicates are displayed and some questions are missing

---

src/etools/applications/field_monitoring/planning/activity_validation/permissions_matrix.csv
src/etools/applications/field_monitoring/planning/tests/test_views.py

[ch31717] FM: Action point tab activate during data collection

---

src/etools/applications/last_mile/serializers.py
src/etools/applications/last_mile/tasks.py
src/etools/applications/last_mile/templates/emails/wastage_transfer.html

[ch36603] LMSM - Notification: Surplus

---

src/etools/applications/users/mixins.py
src/etools/applications/users/signals.py
src/etools/applications/users/tests/test_views_v3.py

[ch36942]  AMP: Add IP LM Editor role to users

---

src/etools/applications/last_mile/admin.py
src/etools/applications/last_mile/serializers.py
src/etools/applications/last_mile/tests/test_views.py

+  remove to_representation from ItemSerializer

LMSM-import-items

---

src/etools/applications/core/middleware.py
src/etools/applications/last_mile/admin.py
src/etools/applications/last_mile/views_ext.py
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/validation/interventions.py
src/etools/applications/partners/views/interventions_v3_actions.py
src/etools/applications/users/mixins.py
src/etools/applications/utils/helpers.py
src/etools/config/settings/base.py

[ch35966]
[ch34825]
[ch37182]
[ch37181]
[ch37185]
[ch37180]

Various Fixes

---

src/etools/applications/partners/locale/ar/LC_MESSAGES/django.po
src/etools/applications/partners/locale/es/LC_MESSAGES/django.po
src/etools/applications/partners/locale/fr/LC_MESSAGES/django.po
src/etools/applications/partners/locale/pt/LC_MESSAGES/django.po
src/etools/applications/partners/locale/ru/LC_MESSAGES/django.po
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py

Story details: https://app.shortcut.com/unicefetools/story/32250

[PMP] Supply list upload: Successful upload for inappropriate list

---

src/etools/applications/reports/models.py
src/etools/applications/reports/serializers/v2.py
src/etools/applications/reports/tests/test_views.py

[ch37072] PMP: prevent adding duplicated name disaggregation

---

src/etools/applications/last_mile/serializers.py
src/etools/applications/last_mile/tests/test_views.py

LMSM - Make Location Mandatory during checkout

---

src/etools/applications/last_mile/serializers.py
src/etools/applications/last_mile/tests/test_views.py

[ch37444] LMSM - Doc upload mandatory for wastage

---

src/etools/applications/last_mile/serializers.py
src/etools/applications/last_mile/tests/test_views.py
src/etools/applications/last_mile/views_ext.py

1. block checkin of an already checked-in transfer 
2. validate against 0 value on split

[ch37533] LMSM bugs

---

src/etools/applications/last_mile/views.py

[ch37450] 
remove item ordering in list view

LMSM - Sort by expiry date in Checkout 

---

src/etools/applications/field_monitoring/groups.py
src/etools/applications/field_monitoring/planning/filters.py
src/etools/applications/field_monitoring/planning/locale/ar/LC_MESSAGES/django.po
src/etools/applications/field_monitoring/planning/locale/es/LC_MESSAGES/django.po
src/etools/applications/field_monitoring/planning/locale/fr/LC_MESSAGES/django.po
src/etools/applications/field_monitoring/planning/locale/pt/LC_MESSAGES/django.po
src/etools/applications/field_monitoring/planning/locale/ru/LC_MESSAGES/django.po
src/etools/applications/field_monitoring/planning/serializers.py
src/etools/applications/field_monitoring/planning/tests/test_views.py
src/etools/applications/field_monitoring/tests/factories.py

Story details: https://app.shortcut.com/unicefetools/story/37260

[FM] Validate report reviewer

---

src/etools/libraries/azure_storage_backend.py

Story details: https://app.shortcut.com/unicefetools/story/37680
azure blob storage was updated from 2.1.0 to 12.20.0. those changes were not reflected in etools custom storage

[Develop] unicef-attachments issue on upload

---

src/etools/applications/users/serializers_v3.py
src/etools/applications/users/tests/test_views_v3.py

[ch37461] AMP: allow external users to update their job descriptions

---

src/etools/__init__.py
src/etools/applications/audit/serializers/mixins.py
src/etools/applications/audit/tests/test_views.py
src/etools/config/settings/base.py

Revert "Update develop from staging"

---

src/etools/applications/users/tests/test_views.py
src/etools/applications/users/views.py

[ch38355] User management API: return correct previous and current roles for the given workspace

---

src/etools/applications/users/admin.py
src/etools/config/settings/base.py

add a single realm: override Realm Admin form
str2bool for RESTRICTED_ADMIN

[ch37653] Admin User with RSS group 

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_interventions.py

Story details: https://app.shortcut.com/unicefetools/story/31859
fix actions available for authorized officer

[PMP] Add a review level for the Rep #2

---

src/etools/applications/t2f/tests/test_overlapping_trips.py
src/etools/applications/t2f/tests/test_permission_matrix.py
src/etools/applications/t2f/tests/test_reference_number.py
src/etools/applications/t2f/tests/test_state_machine.py
src/etools/applications/t2f/tests/test_travel_details.py
src/etools/applications/t2f/tests/test_travel_list.py
src/etools/applications/t2f/views/travel.py

[ch38995] T2F: Prevent users from creating visits

---

src/etools/applications/core/data/field_monitoring_questions.json
src/etools/applications/core/data/field_monitoring_questions_es.json
src/etools/applications/core/data/field_monitoring_questions_fr.json
src/etools/applications/field_monitoring/fm_settings/admin.py

[ch38676] FM: add-supply-questions-for-partner-and-output

---

src/etools/applications/last_mile/models.py
src/etools/applications/last_mile/serializers.py
src/etools/applications/last_mile/tasks.py
src/etools/applications/last_mile/templates/emails/wastage_transfer.html

…not to search again in the db the transfer

[LMSM] Transfer notification fix #2

---

src/etools/applications/governments/models.py
src/etools/applications/governments/serializers/result_structure.py
src/etools/applications/governments/tests/factories.py
src/etools/applications/governments/tests/test_results_structure.py
src/etools/applications/governments/urls.py
src/etools/applications/governments/views/gdd.py

[ch39183] GPD sync results structure

---

src/etools/applications/locations/models.py
src/etools/applications/locations/prp_views.py
src/etools/applications/locations/serializers.py
src/etools/applications/locations/tests/test_prp_views.py
src/etools/config/urls.py

[ch39322] PRP endpoint for sync locations

---

src/etools/applications/partners/admin.py

[ch38442] Fixing the autocomplete for partner

---

src/etools/applications/locations/prp_views.py
src/etools/applications/locations/tests/test_prp_views.py

[ch39332] PRP sync only active locations

---

src/etools/applications/audit/models.py
src/etools/applications/audit/tests/test_views.py

[ch38652] FAM- Formula for pending_unsupported_amount is incorrect on the BE

---

src/etools/applications/funds/tests/test_views.py
src/etools/applications/funds/views_ext.py
src/etools/applications/partners/tests/factories.py

[ch37278] FR creation from external also triggers pd auto transition if all reqs are met

---

src/etools/applications/audit/serializers/engagement.py

[ch39585] PMP : add pending unsupported amount column in partner details

---

src/etools/applications/partners/permission_matrix/agreement_permissions.csv
src/etools/applications/partners/permissions.py

[ch38335] PMP: An issue with signed PCA not moving to Ended

---

src/etools/applications/field_monitoring/planning/templates/fm/visit_pdf.html

[ch39799] FM: css-styling displayed in pdf export

---

src/etools/applications/governments/notifications/gdd-amendment-added.py
src/etools/applications/governments/notifications/gdd-created-updated.py
src/etools/applications/governments/notifications/gdd-draft.py
src/etools/applications/governments/notifications/gdd-ended-frs-outstanding.py
src/etools/applications/governments/notifications/gdd-partner_accepted.py
src/etools/applications/governments/notifications/gdd-partner_unlocked.py
src/etools/applications/governments/notifications/gdd-past-start.py
src/etools/applications/governments/notifications/gdd-prc-review-notification.py
src/etools/applications/governments/notifications/gdd-prc_review_sent_back.py
src/etools/applications/governments/notifications/gdd-review-notification-authorized-officer.py
src/etools/applications/governments/notifications/gdd-send_to_partner.py
src/etools/applications/governments/notifications/gdd-send_to_unicef.py
src/etools/applications/governments/notifications/gdd-unicef-accepted-behalf-of-partner.py
src/etools/applications/governments/notifications/gdd-unicef_accepted.py
src/etools/applications/governments/notifications/gdd-unicef_accepted_review.py
src/etools/applications/governments/notifications/gdd-unicef_cancelled.py
src/etools/applications/governments/notifications/gdd-unicef_pending_approval.py
src/etools/applications/governments/notifications/gdd-unicef_rejected_review.py
src/etools/applications/governments/notifications/gdd-unicef_sent_for_review.py
src/etools/applications/governments/notifications/gdd-unicef_suspended.py
src/etools/applications/governments/notifications/gdd-unicef_terminated.py
src/etools/applications/governments/notifications/gdd-unicef_unlocked.py
src/etools/applications/governments/notifications/gdd-unicef_unsuspended.py

Update notifications texts from GDD to GPD, from Government Digital Document to Government Programme Document

Update notifications texts from GDD to GPD, from Government Digital Document to Government Programme Document

---

src/etools/applications/partners/tests/test_v3_pmp_dropdowns.py
src/etools/applications/partners/views/v3.py

[ch39749] Added gpd status for front-end filtering

---

src/etools/applications/governments/models.py
src/etools/applications/governments/serializers/gdd.py
src/etools/applications/partners/tests/test_v3_pmp_dropdowns.py
src/etools/applications/partners/views/v3.py

[ch39749] add gpd statuses for filter

---

src/etools/applications/governments/models.py
src/etools/applications/governments/permissions.py
src/etools/applications/governments/tests/factories.py
src/etools/applications/governments/tests/test_api_amendments.py
src/etools/applications/users/models.py

[ch39905] GPD date last amended on the timing tab

---

src/etools/applications/governments/permissions.py

[ch39972] new permission if branch for gdd-s partner staff

---

src/etools/applications/last_mile/views.py

This reverts commit 155d895b18cdc908a1aaa6f41edc0be4bcc8a610, reversing changes made to e608128c10edb53dc257683edc2db44b67d03ec5.

Develop - fixing incorrect merge

---

src/etools/applications/vision/admin.py
src/etools/applications/vision/tests/test_admin.py

- added view only permission for vision logs

added view only permission for vision logs
