unicef/etools

EquiTrack/partners/models.py

When I create an intervention associated to SSFAs, MOUs, or ICs, the: 
- signed by partner
- signed by partner date
- signed by UNICEF
- signed by UNICEF date
- start date
- end date 
fields should be auto populated from the same fields found in the agreement details.

added autopopulate intervention from agreement details

---

EquiTrack/assets/css/main.css
EquiTrack/requirements/base.txt
EquiTrack/templates/admin/base_site.html
EquiTrack/templates/base.html

Remove "Testing Environment" top bar.
Change banner in localhost, etools-dev, and etools-staging to be red
and display "Local Testing Environment", "Develop Testing Environment",
and "Staging Testing Environment" on banner respectively.

refractor(templates/admin): change test environments to have more obvious headers

---

EquiTrack/reports/fixtures/initial_data.json

PL19
Do we need to do anything else other than letting users put an activity to parent and use SubActivity as type? I can see there's some logic based on ResultType in `ProgrammeSynchronizer._save_records(self, records)`.

feature add result type subactivity

---

EquiTrack/EquiTrack/settings/production.py

This PR addresses using redis as Django cache backend in the production environment.
It expects to get REDIS_CACHE_ADDRESS as environment variable.

Django settings CACHES for redis in production [#216]

---

EquiTrack/partners/models.py
EquiTrack/partners/permissions.py
EquiTrack/partners/serializers/serializers_v2.py
EquiTrack/partners/tests/test_views.py
EquiTrack/partners/views/views_v2.py

- We originally agreed to put attached_agreement field but am removing from serializer because it will take time to serialize url from the FileField.
- To speed up API added related manager ind the model and used it in the list view.
- Will be adding another serializer to get all related models serialized for agreements. This will be used to cache all data in the fronted.

Agreements API fixes

---

EquiTrack/requirements/base.txt

This PR addresses a temporary fix for factory-boy library to work until there is a new version to fix it permanently.

Fix - Faker pip requirement overriding

---

EquiTrack/t2f/filters/__init__.py
EquiTrack/t2f/serializers/__init__.py
EquiTrack/t2f/tests/test_travel_list.py
EquiTrack/t2f/urls.py
EquiTrack/t2f/views.py

@robertavram said:
Look at this screen:
https://projects.invisionapp.com/share/XQ90VSSC7#/screens/205455281
notice MonitoringVisits.
Build an api endpoint that takes in a partner organization ID, Gets all the travels with those fields.  Basically what you'll have to do is:
get all The travel_activities that connect to the Partner Oganization.
In order to get the travel you'll have to get all the Travels where the traveller is equal to TravelActivity primary_traveler

Add monitoring visits api

---

EquiTrack/t2f/tests/test_travel_list.py
EquiTrack/t2f/views/dashboard.py

Frontend needs to be aligned.
For travels_by_section that have no Section associated, section_id is null and section_name is "no_section_selected". Frontend should say "No Section Selected" instead of Section name.

Fix trips dashboard no section error

---

EquiTrack/t2f/serializers/travel.py
EquiTrack/t2f/tests/test_state_machine.py

In case of first save and submit, the serialzier threw a 500 because it tried to look up an id which does not exists yet.

fix wrong Q lookup at first save

---

EquiTrack/locations/tests/test_views.py

- In heavy detail tests, replace weak 'assert absence of' test with strong 'assert presence of' test
- consolidated common heavy detail test code into a utility function
- Fix potential bug relying on arbitrary sort order of dict keys
- Fix potential bug where `response.data["name"]` was accessed without prior verification that the `name` key existed
- In all tests in `locations/tests/test_views.py`, replaced hardcoded URLs with Django's `reverse()` function
- Fix 2 flake8 errors (already fixed in PR #630)

Fix some weak locations API tests

---

EquiTrack/funds/tests/test_views.py
EquiTrack/locations/tests/test_views.py
EquiTrack/partners/tests/test_api_interventions.py
EquiTrack/partners/tests/test_exports.py
EquiTrack/partners/tests/test_models.py
EquiTrack/partners/tests/test_views.py
EquiTrack/reports/tests/test_views.py
EquiTrack/t2f/tests/test_state_machine.py
EquiTrack/trips/tests/test_views.py
EquiTrack/users/tests/test_views.py

`assertEquals()` and `assertNotEquals()` were deprecated in Python 2.7.
https://docs.python.org/2/library/unittest.html#deprecated-aliases
This commit changes all instances of these two assertions to their
non-deprecated versions (`assertEqual()` and `assertNotEqual()`).
I used an automated tool to do this --
`find backend/EquiTrack -name "*.py"  | xargs  2to3 -w -n -f asserts`

Update deprecated assertions (READY)

---

EquiTrack/requirements/base.txt

dateutils isn't referenced anywhere in the code that I can find. 
It's a small library that adds some utility functions over and above `python-dateutil`.

Removing unused requirement dateutils.

---

.flake8
EquiTrack/.flake8
EquiTrack/runtests.sh
docs/guidelines.rst

This just adds the ability for flake8 to run on CircleCI (and locally). I expect this build to fail and then I'll update .flake8 to make sure it passes.
I've removed our exclusion of E121 and E126 from the guidelines because apparently there is currently no code violating those rules. Here is the current list of violations (by code type):
```
$ flake8 --statistics --count -qq
47    E111 indentation is not a multiple of four
10    E122 continuation line missing indentation or outdented
39    E127 continuation line over-indented for visual indent
35    E128 continuation line under-indented for visual indent
7     E201 whitespace after '{'
5     E202 whitespace before '}'
1     E203 whitespace before ':'
1     E225 missing whitespace around operator
15    E231 missing whitespace after ':'
9 …
```

Add Flake8 testing to CI

---

EquiTrack/partners/views/v2.py

No functional change. This import was working by luck; the class `Value` is available via `django.db.models.functions` only incidentally. (It's not available there in Django 1.10.) Proper location is `django.db.models`.
https://docs.djangoproject.com/en/1.10/ref/models/expressions/#value-expressions
Also fixed a PEP8 complaint; this file is now flake8 clean.

Move import for Django 1.10 compatibility

---

EquiTrack/EquiTrack/settings/base.py
EquiTrack/partners/migrations/0001_initial.py
EquiTrack/partners/models.py
EquiTrack/requirements/base.txt

Replace 3rd party library `django-hstore` with native Django functionality. (`hstore` has been native since django 1.8)
Removing `django-hstore` removes an impediment to upgrading to Django 1.10. `django-hstore` isn't compatible with Django 1.10. The author is aware of this but has no more time to maintain the module and is looking for a new  maintainer.
https://github.com/djangonauts/django-hstore/issues/154
https://github.com/djangonauts/django-hstore/issues/161
Also make `partners/models.py` flake8 clean (in the 2nd commit).
This PR against `pmp-redesign` replaces PR #753 which did the same thing against `develop`.
This PR is a bit of pain to test because it affects a `0001_initial.py` migration. To test it properly (AFAICT) one has to delete one's database and start fresh to get the …

Replace 3rd party django hstore

---

docs/guidelines.rst

Add a section on exception handling to the coding guidelines doc.
This PR is deliberately against `develop` since the guidelines are being kept up-to-date there (rather than in `pmp-redesign`).

Add recommendations for exception handling to guidelines

---

EquiTrack/partners/tasks.py

Some transitions would not transition properly due to errant query. I found this problem while writing a test for this code (which will appear in a future PR).
Problematic code was this --
```
Intervention.objects.filter(status__in=Intervention.ACTIVE)
```
`Intervention.ACTIVE == 'active'`, so the code above is equivalent to this --
```
Intervention.objects.filter(status__in=[‘a’, ‘c’, ’t’, ‘i’, ‘v’, ‘e’])
```
This code was originally correct but was changed to the incorrect version two weeks ago in https://github.com/unicef/etools/commit/447dae24684806eddd6c10293e6ccef30a921926

Fix bug where interventions would not transition properly due to errant query

---

EquiTrack/.flake8
EquiTrack/workplan/models.py
EquiTrack/workplan/serializers.py
EquiTrack/workplan/tasks.py
EquiTrack/workplan/views.py

Fixes flake8 violations.
Issues for later:
* Don't refer directly to User model
* models.py: Address TODOs
* models.py: Make TextFields not null
* views.py: Address TODOs
* views.py: Remove TaggedNotificationMixin (not used)
* test_views.py: docstrings
* test_views.py: use URL reversal
* test_views.py: remove commented code
* add tests

Cleanup workplan app

---

EquiTrack/EquiTrack/settings/local.py
EquiTrack/audit/tests/test_transitions.py
EquiTrack/partners/tests/test_views.py

This...
1) removes extraneous output from our test output, and
2) makes things about 4 seconds faster because the fixture is loaded once per class, instead of per-testcase.

Quieter audit tests

---

EquiTrack/partners/tests/test_tasks.py

Fix my code that was putting a naive date into a timezone-aware datetime field. When run with warnings enabled, this code produced this 12 of these warnings --
```
RuntimeWarning: DateTimeField Agreement.created received a naive datetime (2017-08-16 00:00:00) while time zone support is active.
```

Fix timezone-aware datetime receiving naive date 

---

EquiTrack/EquiTrack/tests/test_validation_mixins.py
EquiTrack/EquiTrack/validation_mixins.py
EquiTrack/t2f/views/__init__.py
EquiTrack/utils/permissions/tests/test_permission_serializers.py

Three pieces of code in eTools use deprecated Python syntax that raises this when warnings are enabled --
```
DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
```
See second bullet here --
https://docs.python.org/2/whatsnew/2.6.html#deprecations-and-removals
This PR updates the code that uses the deprecated syntax.
I ended up refactoring the definition of some of the custom exceptions in `validation_mixins.py`, so I added a test case for them.
Bonus fixes in `validation_mixins.py` (898595ba56741b9c932338b83352872afb83dc41) -- 
* Fixed a bug in `transition_error_string()` and `state_error_string()`. In the case where each accessed `e.message`, they returned a 2-tuple of `(bool, string)`. In all other cases, the return is a 2-tuple of `(bool, [string])`. Now …

Modernize exception message syntax 

---

EquiTrack/t2f/tests/factories.py

Timestamps were being deliberately localized in the factories. When run with warnings enabled, this generated 102 warnings of this type --
```
RuntimeWarning: DateTimeField FundingCommitment.start received a naive datetime (2017-01-01 00:00:00) while time zone support is active.
```
Per @ewheeler , t2f was deliberately coded this way in anticipation of some change that never came to pass, so it's OK to simply add a UTC timestamp here.

Make naive datetimes TZ-aware in t2f factories

---

EquiTrack/t2f/models.py

Timestamps were being deliberately localized in the t2f models. When run with warnings enabled, this generated 49 warnings of this type --
```
RuntimeWarning: DateTimeField FundingCommitment.start received a naive datetime (2017-01-01 00:00:00) while time zone support is active.
```
Per @ewheeler , t2f was deliberately coded this way in anticipation of some change that never came to pass, so it's OK to simply add a UTC timestamp here.

Make all datetimes in t2f models TZ-aware.

---

EquiTrack/partners/tests/test_models.py

Partners model tests were using TZ-naive timestamps. When run with warnings enabled, this generated about a dozen warnings of this type --
```
RuntimeWarning: DateTimeField FundingCommitment.start received a naive datetime (2017-01-01 00:00:00) while time zone support is active.
```

Use TZ-aware timestamps instead of naive ones in partners model tests

---

EquiTrack/t2f/migrations/0008_auto_20170323_1111.py
EquiTrack/t2f/migrations/0010_fix_clearances.py

Two t2f migrations were filtering instances by comparing naive timestamps against a TZ-aware field. I changed them to use TZ-aware timestamps.

Change TZ-naive datetimes to plain dates in t2 migrations

---

EquiTrack/trips/exports.py
EquiTrack/trips/models.py
EquiTrack/trips/serializers.py

Switch to `unicode(object)` rather than `object.__unicode__()`. The latter can't be automatically translated by the 2to3 tool. No functional change.

Fix trips unicode references (Python 3 compatibility)

---

EquiTrack/partners/tests/test_views.py

This fixes a test that I recently added which sometimes breaks because it assumes that files uploaded to Django will retain their exact name which is not true. Django reserves the right to change the name of uploaded files to avoid name conflicts. At present it just adds a random 7-character string to the existing filename if there's a conflict; the code is here --
https://github.com/django/django/blob/1.9.13/django/core/files/storage.py#L84
Rather than write a test that depends on the exact behavior of Django's internals, this PR removes filename checking from the test.

Fix partners attachment test

---

EquiTrack/EquiTrack/factories.py
EquiTrack/funds/models.py
EquiTrack/funds/tests/test_models.py

Convert all models in `funds` to Python 3-compatible `__str()__` methods using Django's `@python_2_unicode_compatible decorator` while retaining compatibility with Python 2.
Add non-ASCII tests for `str()` and `unicode()` methods for each model.
Add factories as necessary for tests.

Convert funds models to Python 3-compatible str() methods

---

EquiTrack/EquiTrack/factories.py
EquiTrack/locations/models.py
EquiTrack/locations/tests/test_models.py

Convert all models in `locations` to Python 3-compatible `__str()__` methods using Django's `@python_2_unicode_compatible decorator` while retaining compatibility with Python 2.
Add non-ASCII tests for `str()` and `unicode()` methods for each model.
Add factories as necessary for tests.

Convert locations models to Python 3-compatible str() methods

---

EquiTrack/EquiTrack/tests/test_all_models.py

To ensure Python 3 compatibility, all eTools models need to implement Django's `@python_2_unicode_compatible` decorator. This test ensures that every model in eTools does so. 
At present, all eTools models are given a special pass via the `EXCLUDED_PACKAGES` list (in this test module) because none of them implement the decorator yet. As I add the decorator to models one by one, I'll remove them from the `EXCLUDED_PACKAGES` list.

Add meta-test to ensure str/unicode Python 3 compatibility 

---

EquiTrack/notification/models.py
EquiTrack/notification/tests/test_email.py
EquiTrack/notification/tests/test_models.py

Convert `Notification` model to Python 3-compatible `__str()__` methods using Django's `@python_2_unicode_compatible decorator` while retaining compatibility with Python 2.
Add non-ASCII tests for `str()` and `unicode()` methods. 
Remove redundant test from `test_email.py`.

Convert Notification model to Python 3-compatible __str()__ method

---

EquiTrack/audit/tests/test_views.py
EquiTrack/partners/tests/test_api_interventions.py
EquiTrack/partners/tests/test_views.py
EquiTrack/t2f/tests/test_dashboard.py
EquiTrack/users/tests/test_views.py

`assertEquals()` and `assertNotEquals()` were deprecated in Python 2.7.
https://docs.python.org/2/library/unittest.html#deprecated-aliases
This commit changes all instances of these two assertions to their non-deprecated versions (`assertEqual()` and `assertNotEqual()`). No functional change.
I used an automated tool to do this --
```
find backend/EquiTrack -name "*.py" | xargs 2to3 -w -n -f asserts
```
I already cleaned these up in #724 but new ones have snuck back in since then.

Replace deprecated assertion methods with preferred alternatives

---

EquiTrack/partners/models.py
EquiTrack/partners/permissions.py
EquiTrack/partners/views/agreements_v2.py
EquiTrack/partners/views/interventions_v2.py
EquiTrack/partners/views/partner_organization_v2.py
EquiTrack/partners/views/prp_v1.py
EquiTrack/partners/views/v2.py
EquiTrack/reports/views/v2.py

In `partners/permissions.py`, changed this --
`PartneshipManagerPermission`
to this --
`PartnershipManagerPermission`   (<== added 'r')
And this --
`PartneshipManagerRepPermission`
to this --
`PartnershipManagerRepPermission`    (<== added 'r')
And in `partners/models.py`, changed this --
`ASSESMENT_TYPES`
to this --
`ASSESSMENT_TYPES`    (<== added 'S')
Naturally this affected a lot of other files...
Sorry, I know this is annoying but I figure it's best to correct these before they spread even further.

Fix three spelling typos in partners (PRP-refactor)

---

EquiTrack/EquiTrack/urls.py

in addition to the swagger UI we expose for API documentation, we can easily expose the same info in two standard json formats in case anyone would like to explore the API with clients/tools that support these standards

expose json api schemas

---

EquiTrack/partners/tests/test_views.py
EquiTrack/partners/views/partner_organization_v2.py

allow deletion of partners that have agreements in `draft` status
fixes unicef/etools-issues#757

allow partner deletion with draft pcas

---

EquiTrack/partners/tests/test_api_prp.py
EquiTrack/partners/tests/test_utils.py
EquiTrack/reports/serializers/v2.py
EquiTrack/reports/tests/test_serializers.py
EquiTrack/reports/tests/test_views.py
EquiTrack/reports/urls_v2.py
EquiTrack/reports/views/v2.py

Took a crack at what I thought these two items meant:
- Endpoint for getting/patching/deleting disaggregations (disabled deleting)
- Test endpoint for getting/patching/deleting disaggregations
@robertavram cc @vkurup since you wrote the other Disaggregations endpoint / tests.

API endpoints for retreiving and updating Disaggregations

---

EquiTrack/EquiTrack/tests/mixins.py
EquiTrack/partners/serializers/prp_v1.py
EquiTrack/partners/tests/data/prp-intervention-list.json
EquiTrack/partners/tests/test_api_prp.py
EquiTrack/partners/tests/test_exports.py
EquiTrack/partners/tests/test_views.py
EquiTrack/partners/views/helpers.py
EquiTrack/partners/views/partner_organization_v2.py
EquiTrack/partners/views/prp_v1.py

this implements pagination and date based filtering/values from https://github.com/unicef/etools/issues/934
It includes everything in https://github.com/unicef/etools/pull/938 so I wouldn't have to deal with merge conflicts, but is separate in case we want to change the pagination format or date params.

add pagination and filtering to prp API

---

EquiTrack/EquiTrack/factories.py
EquiTrack/partners/models.py
EquiTrack/partners/tests/test_models.py

Before it appeared that if provided with a planned visit
we would exclude that provided planned visit from the query, and then
add it to the summed result from the query.
This had the side affect of including provided planned visits that
had years for non current years.
It seems simpler to just query all the planned visits for the current year
and sum their programmatic value.

Refactor planned visits on PartnerOrganization

---

EquiTrack/requirements/base.txt

Also removed django-jsonfield requirements, was required by
django-activity-stream only. Rather use native django json field.

Remove django-activity-stream requirement

---

EquiTrack/EquiTrack/tests/test_all_models.py
EquiTrack/t2f/models.py
EquiTrack/t2f/tests/test_models.py

Convert all models in `t2f` to Python 3-compatible `__str()__` methods using Django's `@python_2_unicode_compatible decorator` while retaining compatibility with Python 2.
Add non-ASCII tests for `str()` and `unicode()` methods for each model.
Only 3 models in `t2f` have `__str__()` methods, so this is a small change.

Convert t2f models to Python 3-compatible str() methods

---

EquiTrack/EquiTrack/tests/test_all_models.py
EquiTrack/partners/models.py
EquiTrack/partners/tests/factories.py
EquiTrack/partners/tests/test_models.py

Convert all models in `partners` to Python 3-compatible `__str()__` methods using Django's `@python_2_unicode_compatible decorator` while retaining compatibility with Python 2.
- Add non-ASCII tests for `str()` and `unicode()` methods for each model. 
- Add factories as necessary for tests to new file `partners/tests/factories.py` (4ef366a5723e3b6c82718f85adb4990da663c0df)
- Fix a small bug in `InterventionBudget` where `str()` would fail if called on an instance that hadn't yet been saved. (f18c9acf2cc38cdf9680fca3b5ce63c27827cba9)
- In `test_models.py`, changed `test_unicode()` methods to `test_str()` (36d2485f2cae56d31bd59886b94fbb2933b337d3)

Make partners models Python 2/3 compatible

---

EquiTrack/audit/tests/test_views.py

Sort lists of ids before comparing to ensure database randomness doesn't cause spurious test failure.
This test has contained this flaw for 6 months but it just now started failing on my machine. Curious!

Fix spurious test failure in audit

---

EquiTrack/EquiTrack/settings/base.py
EquiTrack/requirements/base.txt

Being able to upgrade Django 1.10 requires us to either replace djangosaml2 or update it.
If we want to update it, I [forked](https://github.com/unicef/djangosaml2) the maintained version of djangosaml2 which is Django 1.10 compatible and applied the tweaks that had been made to our current version of djangosaml2.
This pull request is against develop and replaces https://github.com/unicef/etools/pull/1117

Upgrade djangosaml2

---

EquiTrack/vision/tasks.py
EquiTrack/vision/tests/test_tasks.py

* Use Celery's retry feature to retry vision sync tasks that fail, at
least a few times.
* Remove some unused code from vision/tasks.py.
Fixes: https://github.com/unicef/etools-issues/issues/1115
Replaces PR: https://github.com/unicef/etools/pull/1178

Retry vision sync tasks on failure

---

EquiTrack/partners/serializers/interventions_v2.py
EquiTrack/partners/tests/test_api_interventions.py
EquiTrack/partners/validation/interventions.py
EquiTrack/partners/views/interventions_v2.py
EquiTrack/reports/serializers/v2.py

Locations and sections now need to be selected on the intervention to
be able to be added on an indicators.
Locations and sections cannot be removed from an intervention if they
are present on any indicator.
Indicators can now be deleted while in status draft

PRP Refactoring validation fixes

---

.circleci/config.yml

If we include the branch name in our cache key, then each new PR will have to reinstall requirements from scratch. In that case, the only benefit of the cache is for the 2nd to nth pushes to that branch.
Since we include the requirements file and the circle CI config file hashes in the cache key, I think that should be sufficient to bust the cache when there are meaningful changes to the build.
Potential savings: about 2-3 minutes for initial PR branches.

CI: less aggressive cache-busting

---

EquiTrack/vision/adapters/programme.py

with 'undefined' INDICATOR_CODE and record with empty INDICATOR_DESCRIPTION

RAMSynchronizer: skip record criteria

---

EquiTrack/EquiTrack/tests/test_all_models.py
EquiTrack/EquiTrack/tests/test_parsers.py
EquiTrack/EquiTrack/tests/test_utils.py
EquiTrack/EquiTrack/tests/test_validation_mixins.py
EquiTrack/audit/tests/test_models.py
EquiTrack/firms/tests/test_utils.py
EquiTrack/funds/tests/test_api.py
EquiTrack/locations/tests/test_models.py
EquiTrack/management/tests/test_api.py
EquiTrack/monitoring/tests/test_checks.py
EquiTrack/partners/tests/test_api_agreements.py
EquiTrack/partners/tests/test_api_interventions.py
EquiTrack/partners/tests/test_api_partners.py
EquiTrack/partners/tests/test_api_pmp.py
EquiTrack/partners/tests/test_models.py
EquiTrack/partners/tests/test_views.py
EquiTrack/publics/tests/test_models.py
EquiTrack/reports/tests/test_models.py
EquiTrack/reports/tests/test_views.py
EquiTrack/users/tests/test_models.py
EquiTrack/vision/tests/test_client.py
EquiTrack/vision/tests/test_models.py
EquiTrack/vision/tests/test_tasks.py
EquiTrack/vision/tests/test_utils.py

Fix test that dirties the database, breaking --keepdb.
monitoring.tests.test_checks.TestCheckDB creates user objects,
but was subclassing unittest.TestCase. Change to BaseTenantTestCase.
The rest of the changes are to other tests that were using
unittest.TestCase. Changing them to django.tests.SimpleTestCase
will result in the tests failing if anything in them changes the
database, so we'll know they need to be changed to BaseTenantTestCase.
Also use BaseTenantTestCase for one vision test that fails otherwise (not
sure why)

Fix dirty test

---

EquiTrack/partners/tests/test_api_interventions.py
EquiTrack/partners/urls_v2.py

[ch4968] This adds a test to reproduce the problem we were seeing,
then changes a couple of URLs in the API so it stops happening.
Warning: this could be a breaking change if anyone is already
using these API endpoints. But they are quite new, so hopefully
not.
See also:
* https://app.clubhouse.io/unicefetools/story/4968/swagger-issue-typeerror-link-object-does-not-support-item-assignment
* https://github.com/marcgibbons/django-rest-swagger/issues/702

Fix for swagger exception

---

EquiTrack/azure_graph_api/tests/test_utils.py

A couple of tests were failing when using `--keepdb` flag

Update azure graph api tests to work with --keepdb test flag

---

EquiTrack/EquiTrack/settings/production.py

Cryptography was expecting the key data to be binary.

[ch5158] Fix production settings/cryptography with Python 3

---

EquiTrack/vision/adapters/funding.py
EquiTrack/vision/tests/test_adapter_funding.py

https://sentry.io/unicef-jk/etools-staging/issues/501462231/
https://app.clubhouse.io/unicefetools/story/4978/fr-handler-none-values-failing-on-frs

[ch4978] Fix exception in vision funding adapter

---

EquiTrack/attachments/serializers_fields.py
EquiTrack/attachments/tests/test_serializers_fields.py
EquiTrack/tpm/tests/test_views.py

[ch5047]
Not able to reproduce the issue being seen by user. Has the patch/fix for the random upload issue been pushed to staging environment?
This pull request includes a test that was added, to test the uploading/adding of a file for an activity. In an attempt to reproduce the issue/error.
The other tweak is an update on a validation message

Test TPM activity attachments

---

EquiTrack/partners/tasks.py
EquiTrack/partners/tests/test_tasks.py

Update the parameter in `copy_all_attachments` call in parnters tasks

Fix copy attachments partner task

---

src/etools/applications/users/admin.py
src/etools/applications/users/templates/admin/users/country/change_form.html
src/etools/applications/users/tests/test_admin.py

On the change page in the admin for the users Country model, add a
button that updates the HACT values for the current country, or if the
current country is the global/public country, schedules tasks to
update all the countries.

[ch5698] Add HACT update button to country page

---

src/etools/applications/partners/serializers/fields.py
src/etools/applications/partners/tests/test_export_partner.py

[ch6043]
HactValuesField was receiving objects still in json format. 
Looks like this happens when hact_values is set as `json.dumps('<dict>')` instead of just passing in the `<dict>` directly and letting the field handle the json encoding.

Update hact values field to better handle obj in json format

---

src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_models.py

[ch5982]
Government type orgnizations can not set planned visit hact values.

Allow planned visit hact values to be set for government types

---

src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/api_v2_agreements.response.json
src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/api_v2_agreements_amendments.response.json
src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestAPIAgreements/fixtures.json
src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/api_v2_partners_not_programmatic_visit.response.json
src/etools/applications/partners/tests/_api_checker/etools.applications.partners.tests.test_api/TestPartners/fixtures.json
src/etools/applications/partners/tests/test_api.py
src/requirements/test.txt

Here's an update, adding tests for 2 API endpoints:
- `agreement-amendment-list`
- `partner-list-not-programmatic-visit`
Wanted to start small, to make sure I was doing this correctly. A few notes:
- This allows us to test GET endpoints, but not POST/DELETE, etc. Maybe that's obvious, but just wanted to be clear about it.
- I don't have a good sense of when to use ApiChecker vs ViewSetChecker

API Checker trial

---

src/etools/applications/attachments/serializers.py

Get or create attachment file type when associating attachment to model.
Save having to create a data migration each time a new attachment associated by coded generic relation.

Add attachment file type if it does not exist

---

src/requirements/base.txt
src/requirements/input/base.in
src/requirements/test.txt

[ch7200]
Fixes TypeError handling in attachment validation
See attachments library changes: https://github.com/unicef/unicef-attachments/commits/master

Update unicef-attachments to 0.2.4

---

src/etools/applications/tpm/tests/test_views.py
src/etools/applications/tpm/views.py

fixed
```
AssertionError at /api/tpm/visits/activities/sections/
The `request` argument must be an instance of `django.http.HttpRequest`, not `rest_framework.request.Request`.
```
inside tpm module

Fix AssertionErrror on incorrect request type in tpm visits subviews

---

src/etools/applications/partners/utils.py

[ch7331]
This is just to copy old records to new structure. So having multiple records is fine, so ignored.

Handle multiple records in copy_attachments

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/urls_v2.py
src/etools/applications/partners/views/interventions_v2.py
src/etools/applications/reports/models.py
src/etools/applications/reports/serializers/v2.py

Fixes [CH 7155]
new edpoint `/api/v2/interventions/[intervention_id]/output_cp_indicators/[cp_output_id]/`
will return a 404 or indicators and output name as follows:
```
{
"ram_indicators": [
{
"indicator_name": "[Inactive] Number and percentage of UNICEF-targeted children receiving psychosocial support"
},
{
"indicator_name": "[Inactive] Number and percentage of UNICEF-targeted separated and unaccompanied children receiving alternative care services"
},
{
"indicator_name": "[Inactive] Percentage and number of UNICEF-targeted children and women in humanitarian situations who experience GBV receiving multisectoral support services (health, psychosocial, livelihood/economic strengthening and justice)"
}
],
"cp_output_name": "CHILD PROTECTION IN EMERGENCIES"
}
```

Ram indicators endpint

---

src/etools/applications/partners/serializers/partner_organization_v2.py
src/etools/applications/partners/tests/test_views.py

[ch5112]
Looks like you are also able to search on `vendor_number` with `vendor_number__icontains`

Add vendor number to partner dashboard

---

src/etools/applications/attachments/tests/factories.py
src/etools/applications/tpm/serializers/attachments.py
src/etools/applications/tpm/tests/test_views.py
src/etools/applications/tpm/urls.py
src/etools/applications/tpm/views.py

Added new endpoint `api/v2/tpm/visits/<visit-id>/links` that provides a list of attachment links for all the activities associated with the visit. 
Also updated the results to include `source` and `activity_id`
These changes were made to help Marko on the frontend

TPM attachment updates

---

src/etools/applications/partners/tests/test_api_agreements.py
src/etools/applications/partners/utils.py

[ch7539]
Need to pass a list of recipients to send_notification_with_template
Should update the library to validate/convert this `recipients` param to list if a str

Ensure we pass a list of recipients to send_notification_with_template

---

src/etools/applications/tpm/serializers/attachments.py
src/etools/applications/tpm/tests/test_views.py

[ch8861]
`InterventionAttachments` have a `type` field that needs to be used for `file_type`

Use correct file type for TPMAttachmentLinks

---

Dockerfile-dev

Locally I was having issues re-building backend container, as the REQUIREMENTS_FILE env was not being set correctly.

Update Dockerfile-dev to set REQUIREMENTS_FILE env var

---

src/etools/applications/reports/serializers/v2.py
src/etools/applications/reports/tests/test_serializers.py

[ch9149]
Update indicator validation
Allowed to change target "v" denominator only if intervention is draft or signed or active and in amendment mode.
Allowed to change target "d" denominator only if intervention is draft or signed

Change indicators amendment

---

src/etools/applications/reports/tests/test_serializers.py

Set value of target specifically, remove chance of values matching and causing test to fail
`AppliedIndicatorFactory` bt default sets `target` `d` value to values between `0 - 5` and the test was using value of `1`, so there was a 20% chance that test would fail.
Specifically setting the target value, so test is more robust now.

Update AppliedIndicatorSerializer test to be more robust

---

src/etools/applications/t2f/tests/factories.py

When running tests on the last day of the year, there is an issue with the fuzzy dates where start value > end value.

Fix factories to handle running tests on last day of the year

---

src/etools/applications/partners/admin.py

[ch9257][ch9315]
`InterventionAttachments` are saved correctly to `Attachments` table via the admin

Intervention attachment admin

---

src/etools/applications/partners/admin.py

[ch9315]
Fix issue where `code` was not being set in formset
See https://sentry.io/share/issue/16732112047f49d993d80c6b152e6fcf/

Ensure code is set for Intervention Attachment formset

---

src/etools/applications/audit/admin.py
src/etools/applications/audit/forms.py
src/etools/applications/t2f/admin.py
src/etools/applications/t2f/forms.py

[ch9782]
If `travel_activity` is not set record is not considered a T2FActionPoint, rather just a ActionPoint.
Hence the snapshot fails to find the record, when creating the delta.

Travel Activity is required for T2FActionPoint models

---

src/etools/applications/partners/admin.py

This was causing an error when attempting to view the admin page

Remove attachment_file from list display in InterventionAttachment admin

---

src/etools/applications/t2f/serializers/travel.py
src/etools/applications/t2f/tests/test_overlapping_trips.py

[ch10004]
Ensure overlapping dates are validated/checked in Approved, and Completed status changes as well.
There is a `validate_itinerary` method, which is used for transition to `Submitted` status, I'd recommend moving the validation in the serializer to this, and using this validation for the other transitions `Approved` and `Completed`.
Kept this PR simply as I believe we're wanting to make a quick release.

Validate overlapping dates in Approved, and Completed status as well

---

src/etools/applications/partners/utils.py

[ch10191]
- strip time from the datetime used in the check, so it works exactly like before, just timezone aware

Fixed datetime less than check in 'send_intervention_draft_notification'

---

src/etools/config/settings/base.py
src/etools/libraries/redis_cache/base.py

[ch11092]
If there is a connection error with redis/cache, then continue as normal.
To test locally, comment out the `CACHE` setting in `src/etools/config/settings/local.py` and make sure redis is not up.
The following tests will fail, as they are actually testing caching;
```
src/etools/applications/environment/tests/test_models.py:85:    def test_is_active_function_cached(self):
src/etools/applications/environment/tests/test_models.py:100:    def test_user_set_is_cached(self):
src/etools/applications/environment/tests/test_models.py:109:    def test_empty_user_set_is_cached(self):
src/etools/applications/environment/tests/test_models.py:117:    def test_group_set_is_cached(self):
src/etools/applications/environment/tests/test_models.py:276:    def …
```

Gracefully handle redis being down

---

src/etools/applications/psea/serializers.py

Cancelled action should not be available in `Cancelled`, and `Submitted` states

Clean up PSEA available actions for cancelled status

---

src/etools/applications/action_points/tasks.py

Correct issue on `Global` tenant schema, now exclude that schema from task
```
UndefinedTable: relation "action_points_actionpoint" does not exist
LINE 1: ...ion_points_actionpoint"."date_of_completion" FROM "action_po...
^
File "django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "newrelic/hooks/database_psycopg2.py", line 51, in execute
**kwargs)
File "newrelic/hooks/database_dbapi2.py", line 25, in execute
*args, **kwargs)
```

Exclude Global tenant from overdue notifications on action_points task

---

src/etools/applications/psea/models.py
src/etools/applications/psea/notifications/assessment-assigned.py
src/etools/applications/psea/notifications/assessment-final.py
src/etools/applications/psea/notifications/assessment-rejected.py
src/etools/applications/psea/notifications/assessment-submitted.py
src/etools/applications/psea/signals.py
src/etools/applications/psea/tests/test_models.py
src/etools/applications/psea/tests/test_views.py

[ch16110]
Need to ensure that `update_notifications` is run when updating the various regions. Appears that this was not done on the previous release to staging as email template is showing old template.
There are no HTML versions of these psea notifications, are we wanting that?

Update get mail context methods to not pass in objects

---

Pipfile
Pipfile.lock

Removes the attachment update endpoint

Update unicef attachments reqs to 0.7.0

---

src/etools/applications/field_monitoring/planning/activity_validation/validations/basic.py
src/etools/applications/field_monitoring/planning/tests/test_models.py

ignoring outputs not connected to the current country programme while validating monitored entities relations
clubhouse#17914

[Field Monitoring] Fix unlinked pd/ssfa validation

---

src/etools/applications/partners/serializers/prp_v1.py
src/etools/applications/partners/views/prp_v1.py

[ch20711]
Use `values()` query for location data in `PRPIndicatorSerializer` sub-serializer.
Locally endpoint was taking ~12s before changes and now taking ~3s

Remove prefetching of locations in prp interventions endpoint

---

src/etools/applications/core/views.py
src/etools/applications/field_monitoring/data_collection/views.py
src/etools/applications/reports/tests/test_views.py
src/etools/applications/reports/views/v2.py

[ch17961]
The default permission class is `IsAuthenticated`
Fixed all permission_classes that attempted to override this default still included `IsAuthenticated` permissions.
The following places were specific about providing "open" access;
- https://github.com/unicef/etools/blob/develop/src/etools/applications/field_monitoring/data_collection/views.py#L71
- https://github.com/unicef/etools/blob/develop/src/etools/applications/core/views.py#L25
- https://github.com/unicef/etools/blob/develop/src/etools/applications/partners/views/prp_v1.py#L23
Are these places ok to be more "open"?

Ensure IsAuthenticated permissions is used

---

src/etools/applications/partners/migrations/0061_auto_20200914_0758.py

Missed that `total_local` field does not have a default value either.

[ePD] InterventionBudget data migration tweak

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_interventions.py

[ch23136]
Did not modify the fields `requesting_officer`, and `approving_officer` on Assessment model, not sure if we want those changed as well?

[ePD] Update intervention user fields to use MinimalUserSerializer

---

src/etools/applications/audit/purchase_order/synchronizers.py

Insight behavior is a bit confusing: if the PO has one item 'rows' returns a single dict else a list of dicts 
https://github.com/unicef/unicef-vision/pull/18

Hotfix: POSync: temporary patch for unicef-vision

---

src/etools/applications/partners/tests/test_v3_intervention_lower_results.py
src/etools/applications/partners/views/interventions_v3.py
src/etools/applications/reports/views/v2.py

[ePD] Residual 'Unassociated to CP Output' after Partner user adds and then deletes a PD output

---

src/etools/applications/partners/serializers/interventions_v2.py
src/etools/applications/partners/tests/test_api_interventions.py

Story details: https://app.shortcut.com/unicefetools/story/26828

[PMP] [ch26828 - 1] Disallow similar pairs of intervention + cp output for result links

---

src/etools/applications/partners/amendment_utils.py
src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_api_amendments.py
src/etools/applications/partners/tests/test_v3_interventions.py

don't sync submission_date back from amendment. don't update value if already set

[ePD] Accept on behalf, submission date

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_api_amendments.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/tests/test_v3_serializers_intervention.py
src/etools/applications/partners/views/interventions_v2.py
src/etools/applications/partners/views/interventions_v3_actions.py

A non focal point UNICEF user should not be able to:
- delete an active amendment (where he is not focal point)
- suspend or terminate a PD (where he is not focal point)

[ePD] Non Focal Point UNICEF user permission issues

---

src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py

[ch28014] 403 instead 500 for Anonymous user on /api/pmp/v3/interventions/{pk}/pdf/

[ch28014] ePD: sentry-5965: fix 500 for not authenticated user 

---

src/etools/applications/travel/serializers.py
src/etools/applications/travel/tests/test_views.py

[ch28881] Draft trips should be able to be deleted by the **traveler** or the **travel administrator**
For trips list, the permissions field is no longer an empty list, but contains the delete permission:  
```
"permissions": {
"delete": true/false
}
```
@robertavram Not sure on the right approach here, let me know what you think.

Trips list: add delete permission

---

src/etools/applications/partners/serializers/interventions_v3.py
src/etools/applications/partners/tests/test_v3_interventions.py
src/etools/applications/partners/views/interventions_v3.py

[ch29637] 
Csv fails when: 
1. Non printable character is present
2. Char length exceeds db max_length

[ch29637] ePD supply table upload fails

---

src/etools/applications/field_monitoring/fm_settings/serializers.py
src/etools/applications/field_monitoring/fm_settings/tests/test_views.py

Story details: https://app.shortcut.com/unicefetools/story/31814

[FM] Marking a question as inactive for default questions is throwing an error

---

src/etools/applications/audit/purchase_order/admin.py
src/etools/applications/audit/signals.py
src/etools/applications/audit/views.py
src/etools/applications/core/auth.py
src/etools/applications/field_monitoring/planning/models.py
src/etools/applications/partners/models.py
src/etools/applications/partners/synchronizers.py
src/etools/applications/tpm/signals.py
src/etools/applications/tpm/tpmpartners/admin.py
src/etools/applications/tpm/tpmpartners/synchronizers.py
src/etools/applications/tpm/views.py
src/etools/applications/users/admin.py
src/etools/applications/users/mixins.py
src/etools/applications/users/models.py
src/etools/applications/users/notifications/amp_role-update.py
src/etools/applications/users/permissions.py
src/etools/applications/users/serializers_v3.py
src/etools/applications/users/tasks.py
src/etools/applications/users/views_v3.py

[ch31914] 
AMP:
1. Allow list access to users that have active realms in the current context 
2. Adding a user checks for existing user first 
3. Partnership manager role can also add a user -
4. Filter out organizations that have partners marked for deletion 
5. Users blob in list response to contain first and last name instead of name, also add profile.phone_number, job_title 
6. Update user notification: only sent on update 
Audit, Partners, TPMPartners apps :
1. Adding a staff member also sets the organization on the profile 
Azure user mapper: deactivate all realms for past country 
Authentication: Update core.user_details() to set organization on the user profile
Vision Sync: Partner, TPM Partner Synchronizer: when a partner is marked for deletion, deactivate users and all realms …

[ch31914] AMP changes and fixes

---

src/etools/applications/field_monitoring/fm_settings/tests/test_views.py
src/etools/applications/field_monitoring/fm_settings/views.py
src/etools/applications/locations/views.py

previous fix with disabling cache made browser to ignore etag headers at all, so we enable it back. just checking that browser cache data will never be used.

[FM] Sites are not updated when changing the country #2

---

tox.ini

Updates tox whitelist_externals - deprecated from v4.0.0 to allowlist_externals

[fix tests] Tox config updates 

---

src/etools/applications/partners/models.py

[ch33349] Email url broken - it doubles up on the host since intervention function also returns a url with the host

[ch33349] Email url broken - it doubles up on the host since intervention function also returns a url with the host

---

src/etools/applications/users/permissions.py
src/etools/applications/users/tests/test_views_v3.py
src/etools/applications/users/views_v3.py

[ch33790] PME user cannot add a TPM staff member
[ch33798] UNICEF Audit Focal Point user cannot add a Audit staff member

AMP: PME and  UNICEF Audit Focal Point permissions

---

src/etools/applications/partners/exports_v2.py

[ch34079] "Budget export does not show units and other values for the EEPM line items"

[ch34079] "Budget export does not show units and other values for the EEPM line items"

---

src/etools/applications/users/tests/test_views.py
src/etools/applications/users/views.py

[ch35657]
fix for user management API https://excubo.unicef.io/sentry/etools-prod/issues/41532/

[ch35657] User Management API: IntegrityError: duplicate key value violates unique constraint "unique_realm"

---

src/etools/applications/audit/admin.py
src/etools/applications/partners/permissions.py
src/etools/applications/partners/tests/test_api_interventions.py
src/etools/applications/partners/views/v2.py
src/etools/applications/reports/serializers/v2.py
src/etools/applications/reports/views/v3.py
src/etools/applications/users/views.py

[ch35574]
includes fixes for:
https://excubo.unicef.io/sentry/etools-prod/issues/15971/ /api/pmp/v3/interventions/766/reporting-requirements/HR/ start_date is required and cannot be null
https://excubo.unicef.io/sentry/etools-prod/issues/41471/ /admin/audit/spotcheck/ Related Field got invalid lookup: name
https://excubo.unicef.io/sentry/etools-prod/issues/41478/ /api/reports/v3/interventions/results/{pk}/  'AnonymousUser' object has no attribute 'get_partner' 
https://excubo.unicef.io/sentry/etools-prod/issues/33915/  'NoneType' object has no attribute 'name' - user has no country on profile

[ch35574] Sentry issues

---

src/etools/applications/partners/models.py
src/etools/applications/partners/tests/test_models.py

Story details: https://app.shortcut.com/unicefetools/story/37638

[PMP] To change the logic of the system to NOT calculate the planned PVs for canceled PDs

---

pdm.lock
pyproject.toml

Downgrade the version for django-debug-toolbar from 4.3.0 to 4.2.0 because is the latest that work with django-admin-buttons.
django-debug-toolbal 4.4.0 is not working because is using django 5.1 and 4.3.0 is not working with django-admin-buttons.
So this version fit with all requests.

[ch38574]Fix admin models on DEV Env

---

src/etools/applications/last_mile/serializers.py
src/etools/applications/last_mile/tests/test_views.py

As discussed with Tiaan this morning, I added the new field on the endpoint to be able to make difference between RUTF materials on the FE based on the backend configuration.

[ch37587]Add new field on the response API to be able to translate

---

.circleci/config.yml

Objective:
- Only run tests on PRs, not on pushes to branches (even PR merges)
- Pushes (PR merges) should only build and push for develop, staging and master branches.
Changes:
- Updated config to circle_ci v2.1
- Split setup, test, execution into 2 workflows: one for PRs, one for pushes and merges.
- Remove launch of build_and_push job from the test job. Not needed anymore as they're split workflows now.

Updating circle_ci config: avoid test reruns on PR merges
